Create La formazione per autodidatti
Il-Libro-Open-Source/book pull request #146
Opened 2023-10-11 06:36 UTC by halfpass25

Ragazz*, quello che segue è il frammento "introduttivo" della sezione "autodidatti" di cui mi sto occupando. Include un possibile indice di paragrafi che andrò via via sviluppando e chiedo da subito a tutt* aiuto/critica/suggerimenti per gli argomenti che potrei non aver preso in considerazione o che meritino almeno una breve citazione. Grazie per l'attenzione ed il supporto fattivo ;)  / Pasquale

2023-10-12 10:10 UTC, corradopetrelli commented
Ciao Pasquale, ecco i miei feedback e le mie riflessioni:
- Inserisci l'estensione md al file creato
- Utilizza la sintassi markdown (non conosco il tuo background, nel caso ti linko [questa guida](https://www.markdownguide.org/getting-started/))
- Ho visto che anche il capitolo #70 parla di formazione (@passasooz ha già cominciato una prima stesura su #124), non so se vi siete già sentiti a tal riguardo. Lo chiedo solo per evitare ridondanze tra i vari capitoli
- Riguardo i contenuti mi immagino che il target di questo capitolo sia una persona che potrebbe anche non conoscere niente dell'ambito IT. Eviterei di utilizzare termini tecnici quali: "loop", "INSERT", "UPDATE" ecc... perchè noi tecnici sappiamo a cosa ti riferisci ma probabilmente un neofita non capisce ciò che vuoi trasmettere.

Per il resto mi piace il fatto che utilizzi esempi di vita quotidiana come riferimento utile nella valutazione comparata dei vari aspetti del mondo IT.

2023-10-12 12:12 UTC, Cadienvan commented
@corradopetrelli solo una nota: Ho suggerito io di prendersi questo tema in quanto il capitolo "formazione" è già in fase di stesura da due persone, quindi meglio che venga scritto separatamente e poi, se lo si reputa sensato, li si unisce a stesura conclusa.

Per il resto mi torna tutto

2023-10-12 12:15 UTC, corradopetrelli commented
@Cadienvan nessun problema, non ne ero a conoscenza scusate!

2023-10-12 12:53 UTC, Cadienvan commented
Aggiungo a quanto detto da Corrado che abbiamo delle linee guida molto comode da seguire (https://github.com/Il-Libro-Open-Source/book/blob/main/CONTRIBUTING.md e https://github.com/Il-Libro-Open-Source/book/blob/main/GUIDELINES.md) per iniziare come si deve

2023-10-12 14:04 UTC, halfpass25 commented
@corradopetrelli  si, Corrado, provvederò quanto prima a sistemare il markdown.
Per il luogo in cui pubblicare, come da accordi intercorsi con @guizzo @storrisi e @Cadienvan e come ora sai, la #146 sembra essere il posto giusto, salvo poi farne il merge in capitoli/contesti attinenti.
Tengo presente il non utilizzare termini troppo tecnici o quanto meno di renderli alla "parla come se magna" ;)
Lieto di sapere che l'approccio con le similitudini tratte dalla vita quotidiana ti sia piaciuto, dove possibile la falsariga sarà quella.
Grazie per le precisazioni ed i commenti, a presto!

Pasquale

2023-10-12 20:36 UTC, guizzo reviewed
Giusto qualche spazio di troppo qua e là, ed un paio di parole scritte più volte ma in "versioni diverse"

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Impadronirsi dei fondamenti di informatica e programmazione, sia per farne una professione che per  scopi puramente hobbistici,  è certamente un’impresa stimolante ed eccitante, tanto per i risultati
```suggestion
Impadronirsi dei fondamenti di informatica e programmazione, sia per farne una professione che per scopi puramente hobbistici,  è certamente un’impresa stimolante ed eccitante, tanto per i risultati a cui può condurre, quanto per il puro piacere del “viaggio” nella conoscenza che state intraprendendo.
```

Ti è scappato uno spazio di troppo 😉

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Esempio banale ma calzante: una volta mi è capitato di avere a che fare con un’applicazione discretamente complessa nella quale, ad un certo punto del processo, avrei dovuto stabilire in un loop molt
```suggestion
Esempio banale ma calzante: una volta mi è capitato di avere a che fare con un’applicazione discretamente complessa nella quale, ad un certo punto del processo, avrei dovuto stabilire in un loop molto pesante se nel database dovevo effettuare un’operazione di inserimento o di aggiornamento dei dati.
```

In relazione a quanto già detto da @corradopetrelli, propongo la mia suggestion (ma sentiti libero di scartarla qualora avessi delle proposte migliori)

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +E ciò, fece in modo che avessi automaticamente ed a gratis, solo operazioni di UPDATE e quindi potei eliminare tutta una serie di controlli lunghi, complessi, farraginosi e forieri di errori.
```suggestion
E ciò, fece in modo che avessi automaticamente ed a gratis, solo operazioni di aggiornamento e quindi potei eliminare tutta una serie di controlli lunghi, complessi, farraginosi e forieri di errori.
```

Same as above

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Il termine “programmare” è un ombrello enorme che accoglie sotto di se’ innumerevoli sfumature di codice e dunque, sapere con la miglior precisione possibile a quale tipo di programmazione volete ded
```suggestion
Il termine “programmare” è un ombrello enorme che accoglie sotto di se’ innumerevoli sfumature di codice e dunque, sapere con la miglior precisione possibile a quale tipo di programmazione volete dedicarvi, vi tornerà utilissimo per sfrondare l’inutile e farvi invece una lista utilissima degli strumenti dei quali dovreste impadronirvi.
```

Anche qui, uno spazio di troppo

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Non esiste una sola forma di programmazione ma qualunque applicativo (a meno che non vogliate scrivere solo script  bash di amministrazione), di solito ha una “interfaccia utente”, in genere ma non n
```suggestion
Non esiste una sola forma di programmazione ma qualunque applicativo (a meno che non vogliate scrivere solo script bash di amministrazione), di solito ha una “interfaccia utente”, in genere ma non necessariamente anche grafica che è detta “**Frontend**” e tutto quello che succede quando un utente clicca su un pulsante del Frontend; questa parte, è nota come "**Backend**" o retrobottega.
```

Same as above

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Un mio consiglio, opinione del tutto personale, è: evitate come la peste di gettarvi a corpo morto sui numerosi  “frame work” in circolazione.
```suggestion
Un mio consiglio, opinione del tutto personale, è: evitate come la peste di gettarvi a corpo morto sui numerosi “framework” in circolazione.
```

Spazio di troppo, e credo che framework vada scritto senza spazio

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Che siano frame work frontend o back end, è essenziale che prima di utilizzarli vi impadroniate di ciò che c’è alla loro base.
```suggestion
Che siano framework frontend o back end, è essenziale che prima di utilizzarli vi impadroniate di ciò che c’è alla loro base.
```

Same as above

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Che siano frame work frontend o back end, è essenziale che prima di utilizzarli vi impadroniate di ciò che c’è alla loro base.
```suggestion
Che siano frame work frontend o backend, è essenziale che prima di utilizzarli vi impadroniate di ciò che c’è alla loro base.
```

Qui consigli di tenere una linea comune, quindi o parliamo di `front end` e `back end`, oppure parliamo di `frontend` e `backend`; in breve, eviterei di mixare le versioni

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Questo approccio, non solo vi permetterà di comprendere le cose a basso livello, ma, in seguito, quando vi avvicinerete ad un qualunque frame work, vi consentirà di comprenderne molto più rapidamente
```suggestion
Questo approccio, non solo vi permetterà di comprendere le cose a basso livello, ma, in seguito, quando vi avvicinerete ad un qualunque framework, vi consentirà di comprenderne molto più rapidamente e facilmente i suoi “internals”, che sono invariabilmente basati proprio su… le basi.
```

Altro spazio nella parola framework

2023-10-12 20:36 UTC, guizzo commented on La formazione per autodidatti
> +Non posso suggerirvi tecnologie linguaggi  specifici ma posso dirvi che in generale, è vero che dovreste sentirvi molto “falegnami” e sapere quale è l’attrezzo, lo strumento, l’utensile più idoneo ad
```suggestion
Non posso suggerirvi tecnologie o linguaggi specifici ma posso dirvi che in generale, è vero che dovreste sentirvi molto “falegnami” e sapere quale è l’attrezzo, lo strumento, l’utensile più idoneo ad assolvere ad una determinata funzione.
```

2023-10-14 09:43 UTC, BrianAtzori commented
Ciao @halfpass25 da autodidatta ho letto con piacere questa prima stesura e spero prossimamente di riuscire a collaborare e contribuire a questa sezione del libro, in primis perchè anche io ho l'approccio delle metafore sulla quotidianità quando cerco di spiegare qualcosa in ambito IT e soprattutto perchè mi trovo molto d'accordo e in linea con i concetti che hai portato, tra l'altro scrivendo anche molto bene!

Ho letto tutto e ho visto con piacere che sono stati corretti vari typo che avevo notato anche io, secondo me hai fatto un buon lavoro, complimenti :)

2023-10-19 22:36 UTC, fulgido commented on La formazione per autodidatti
> +Fortunatamente, è possibile migliorare le proprie capacità analitiche attraverso un lungo periodo di esercitazione mentre per la creatività… o ce l’hai o non ce l’hai, punto.
Viene spontaneo definire alcune capacità come "innate". E se, come Carol Dweck ci insegna, alcune capacità fossero più presenti semplicemente perché la persona ha fatto più pratica con quella skill? 
In questo modo non trasmetteremo che una persona non creativa non possa diventarlo. Sempre che ovviamente sia una sua priorità migliorare questo aspetto ed è disposta a fare pratica.

2023-10-23 21:57 UTC, ugho16 reviewed
Ho cercato di rendere più inclusivo il linguaggio e corretto altre sottigliezze. Ovviamente sono proposte, vedi tu se e quali vale la pena implementare

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Meglio ancora: dovreste poter guardare il codice –sempre con gli occhi della mente-, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice “ah, si, q
```suggestion
Meglio ancora: dovreste poter guardare il codice –sempre con gli occhi della mente-, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: “Ah, sì, questo codice fa questa cosa ma si può fare meglio/più rapidamente/con meno dispendio di energie e risorse se facessi in quest’altro modo…”
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Non che il mestiere in se’ sia gelido, tutt’altro: a volte l’eleganza di una soluzione ad un problema, può commuovere fino alle lacrime e non per densità semantica condensata in due righe di codice m
```suggestion
Non che il mestiere in sé sia gelido, tutt’altro: a volte l’eleganza di una soluzione ad un problema, può commuovere fino alle lacrime e non per densità semantica condensata in due righe di codice ma per l’idea che dietro quelle due righe di codice c’è stato un guizzo creativo, subito accompagnato da finezza nella tecnica, ma pur sempre prodotto da un essere umano: questo, è il bello ed il romantico di questo mestiere.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Tra l’altro, l’esempio che vi ho appena fornito, mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai prob
```suggestion
Tra l’altro, l’esempio che vi ho appena fornito, mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai problemi** e a seguire, la conoscenza dei metodi/mezzi/strumenti con cui implementare una possibile soluzione (perché sì: “c’è sempre più di un modo per farlo”).
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Un noto adagio recita “**tutti possono programmare, ma non tutti possono diventare programmatori**”.
```suggestion
Un noto adagio recita “**chiunque può programmare, ma non chiunque può diventare developer**”.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Contrariamente a quello che vi aspettereste di sentirvi dire, qui, in questo libro, il mestiere del programmatore è un mestiere molto più **creativo** e molto meno tecnico di quanto si pensi.
```suggestion
Contrariamente a quello che vi aspettereste di sentirvi dire in questo libro, programmare è un mestiere molto più **creativo** e molto meno tecnico di quanto si pensi.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +In due parole: se non siete “naturalmente portati” verso la materia, potete farcela lo stesso, ma la vostra vita professionale sarà una fatica perenne.
```suggestion
In due parole: se non avete una “inclinazione naturalmente” verso la materia, potete farcela lo stesso, ma la vostra vita professionale sarà una fatica perenne.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Vi conviene? Solo perché avete in mente un’immagine “romantica” del programmatore e del suo mestiere, magari tratta dai numerosi film che potreste aver visto?
```suggestion
Vi conviene? Solo perché avete in mente un’immagine “romantica” di chi programma e del suo mestiere, magari tratta dai numerosi film che potreste aver visto?
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Inutile dire che di sola romanticheria non si vive e che spesso e volentieri, anche utilizzando gli strumenti più appropriati e più adatti per sollevarci da lavori ripetitivi, la vita quotidiana di u
```suggestion
Inutile dire che di sola romanticheria non si vive e che spesso e volentieri, anche utilizzando gli strumenti più appropriati e più adatti per sollevarci da lavori ripetitivi, la vita quotidiana da developer non è sistematicamente soggetta a scariche di adrenalina.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Insomma, se alle domande “ho una reale predisposizione?” e “sono disposto ad accettare che il percorso di istruzione che sto per intraprendere non sarà tutto un tappeto di petali di rose?” avete risp
```suggestion
Insomma, se alle domande “Ho una reale predisposizione?” e “Riuscirò ad accettare che il percorso di istruzione che sto per intraprendere non sarà tutto un tappeto di petali di rose?” avete risposto con un SÌ netto e sicuro, siete già a metà dell’opera, congratulazioni!
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +In teoria, nel momento stesso in cui pensate “ah, ora vado a mettere su la caffettiera”, voi tutti avete in mente –senza rendervene conto-, un piano precisissimo che consiste nei passi di
```suggestion
Chiunque può programmare, allora?
In teoria, nel momento stesso in cui pensate “Ah, ora vado a mettere su la caffettiera”, voi tutti avete in mente –senza rendervene conto-, un piano precisissimo che prevede i seguenti passi:
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Questo non vuol dire che un programmatore che esegua i suoi compiti in maniera canonica sia peggiore di uno baciato dalla Musa della Creatività ma è fuori discussione che quest’ultimo avrà una marcia
```suggestion
Questo non vuol dire che chi programma eseguendo i suoi compiti in maniera canonica sia peggiore di una persona baciata dalla Musa della Creatività, ma è fuori discussione che quest’ultima avrà una marcia in più.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Ad ogni modo, a volte è “meglio soli che male accompagnati” e se siete veramente motivati ed appassionati alla materia, anche lo studio e la sperimentazione in solitaria non vi peserà più di tanto.
```suggestion
Ad ogni modo, a volte è “meglio soli che male accompagnati” e con la giusta motivazione e passione per la materia, anche lo studio e la sperimentazione in solitaria non vi peserà più di tanto.
```

2023-10-23 21:57 UTC, ugho16 commented on La formazione per autodidatti
> +Il termine “programmare” è un ombrello enorme che accoglie sotto di se’ innumerevoli sfumature di codice e dunque, sapere con la miglior precisione possibile a quale tipo di programmazione volete ded
```suggestion
Il termine “programmare” è un ombrello enorme che accoglie sotto di sé innumerevoli sfumature di codice e dunque, sapere con la miglior precisione possibile a quale tipo di programmazione volete dedicarvi, vi tornerà utilissimo per sfrondare l’inutile e farvi invece una lista utilissima degli strumenti dei quali dovreste impadronirvi.
```

2023-10-28 07:02 UTC, Cadienvan commented
@ugho16 si sta auto-candidando per il @Il-Libro-Open-Source/drafting-group ahah
Ottimo lavoro!

2023-11-29 13:34 UTC, Cadienvan commented
@halfpass25 ho applicato le modifiche suggerite. Per favore, dai un'occhiata alle guideline che abbiamo linkato e dai un occhio ai capitoli già disponibili così da poter rivedere correttamente il file :)

2023-12-23 14:14 UTC, Cadienvan commented
@halfpass25 credi di poter rimediare con la formattazione a inizio anno prossimo? Così vediamo di portarlo dentro! :D

2024-01-10 16:05 UTC, halfpass25 commented
> @halfpass25 credi di poter rimediare con la formattazione a inizio anno prossimo? Così vediamo di portarlo dentro! :D

Sto tentando di riprendere ora le cose in mano, purtroppo tempo ne ho veramente poco e sta cosa mi piacerebbe portarla a termine molto più rapidamente di quanto voi tutti possiate pensare o desiderare.
Comunque non sto abbandonando la faccenda, tranquilli! ;)

2024-01-13 08:23 UTC, Cadienvan commented
@halfpass25 nessun problema, il mio è un ping perché il capitolo è molto interessante, prenditi il giusto tempo!

2024-05-04 13:19 UTC, Cadienvan commented
Ciao @halfpass25, come va con il contenuto?

Se conti di non avere tempo o disponibilità per portarlo avanti suggerirei in questo momento piuttosto cerco di rimettere in piedi il capitolo io mettendo la corretta formattazione e proviamo a mandarlo in approvazione :)

2024-07-27 13:38 UTC, Cadienvan commented
Ho riportato in piedi il capitolo formattandolo correttamente perché lo reputo di valore. Ho chiesto la review ad alcuni Ambassador, fatevi sotto!

2024-07-27 13:38 UTC, Cadienvan approved these changes

2024-07-27 13:42 UTC, Cadienvan approved these changes

2024-07-27 13:49 UTC, Mik23mik approved these changes

2024-07-31 14:25 UTC, nicolaerario submitted a review, later dismissed
Piccolezze e virgole; comunque un buon lavoro, quindi approvo

2024-07-31 14:25 UTC, nicolaerario commented on docs/it/la-formazione-per-autodidatti.md
> +E ciò, fece in modo che avessi automaticamente ed a gratis, solo operazioni di aggiornamento e quindi potei eliminare tutta una serie di controlli lunghi, complessi, farraginosi e forieri di errori.
Non mi piace particolarmente `a` gratis ed ho spostato qualche virgola che mi avanzava

```suggestion
E ciò fece in modo che avessi automaticamente (e gratis) solo operazioni di aggiornamento e, quindi, potei eliminare tutta una serie di controlli lunghi, complessi, farraginosi e forieri di errori.
```

2024-07-31 14:25 UTC, nicolaerario commented on docs/it/la-formazione-per-autodidatti.md
> +Tra l’altro, l’esempio che vi ho appena fornito, mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai prob
```suggestion
Tra l’altro, l’esempio che vi ho appena fornito mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai problemi** e, a seguire, la conoscenza dei metodi/mezzi/strumenti con cui implementare una possibile soluzione (perché sì: _c’è sempre più di un modo per farlo_).
```

2024-07-31 14:25 UTC, nicolaerario commented on docs/it/la-formazione-per-autodidatti.md
> +Da non sottovalutare, nel 2023, che la pervasività e disponibilità H24 7/7 di una connessione ad internet è di grandissimo aiuto ad un autodidatta, perché le risorse che può reperire in rete, a grati
Come sopra

```suggestion
Da non sottovalutare, nel 2023, che la pervasività e disponibilità H24 7/7 di una connessione ad internet è di grandissimo aiuto ad un autodidatta, perché le risorse che può reperire in rete, gratis o con poca spesa, sono praticamente sterminate e –soprattutto agli inizi-, costituiscono un validissimo aiuto alla comprensione di argomenti che tutto sono meno che romantici.
```

2024-07-31 14:29 UTC, Cadienvan approved these changes

2024-07-31 14:33 UTC, nicolaerario approved these changes

2024-07-31 14:37 UTC, Mik23mik submitted a review, later dismissed

2024-07-31 16:25 UTC, AngeloAvv requested changes
Il capitolo è meraviglioso e superfluido, mi scoccia rompere le scatole solo per piccolezze strettamente legate alla tastiera utilizzata.

Nice job :mechanical_arm:

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +Meglio ancora: dovreste poter guardare il codice –sempre con gli occhi della mente-, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì,
Potremmo trovare un modo per evitare la doppia ripetizione sugli "occhi della mente"?

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +Insomma, se alle domande _Ho una reale predisposizione?_ e _Riuscirò ad accettare che il percorso di istruzione che sto per intraprendere non sarà tutto un tappeto di petali di rose?_ avete risposto
Typo?

```suggestion
Insomma, se alle domande _Ho una reale predisposizione?_ e _Riuscirò ad accettare che il percorso di istruzione che sto per intraprendere non sarà tutto un tappeto di petali di rose?_ avete risposto con un Sì netto e sicuro, siete già a metà dell’opera, congratulazioni!
```

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +Sembra una contraddizione in termini ma in realtà questa frase nasconde una grande verità: al di là di qualunque eccitazione iniziale per la faccenda, è utilissimo essere onesti con se stessi e capir
Mio dubbio: non servirebbe lo spazio fra i trattini?

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +Tra l’altro, l’esempio che vi ho appena fornito mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai probl
Credo ci siano da sostituire gli apostrofi

```suggestion
Tra l’altro, l'esempio che vi ho appena fornito mette in luce che la programmazione, sia pure con una buona dose di creatività, richiede comunque ed in prima istanza un **approccio analitico ai problemi** e, a seguire, la conoscenza dei metodi/mezzi/strumenti con cui implementare una possibile soluzione (perché sì: _c’è sempre più di un modo per farlo_).
```

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +Fortunatamente, è possibile migliorare le proprie capacità analitiche attraverso un lungo periodo di esercitazione mentre per la creatività… o ce l’hai o non ce l’hai, punto.
Vogliamo tenere i tre puntini (unicode) oppure utilizzare i singoli punti?

```suggestion
Fortunatamente, è possibile migliorare le proprie capacità analitiche attraverso un lungo periodo di esercitazione mentre per la creatività... o ce l’hai o non ce l’hai, punto.
```

2024-07-31 16:25 UTC, AngeloAvv commented on docs/it/la-formazione-per-autodidatti.md
> +E dato che le funzioni possono essere molte, questo spiega anche il proliferare dei frameworks e la necessità di sapere almeno _che cosa fanno_, per quale compito meglio si prestano.
Gli inglesismi andrebbero utilizzati al singolare

```suggestion
E dato che le funzioni possono essere molte, questo spiega anche il proliferare dei framework e la necessità di sapere almeno _che cosa fanno_, per quale compito meglio si prestano.
```

2024-07-31 19:27 UTC, Cadienvan commented on docs/it/la-formazione-per-autodidatti.md
> +Sembra una contraddizione in termini ma in realtà questa frase nasconde una grande verità: al di là di qualunque eccitazione iniziale per la faccenda, è utilissimo essere onesti con se stessi e capir
```suggestion
Sembra una contraddizione in termini ma in realtà questa frase nasconde una grande verità: al di là di qualunque eccitazione iniziale per la faccenda, è utilissimo essere onesti con se stessi e capire - magari facendosi aiutare da chi può valutare con obiettività e cognizione di causa la vostra predisposizione -, se effettivamente la programmazione può essere per voi una strada serena o se è destinata a trasformarsi in una fatica improba, costellata solo di frustrazioni.
```

Hai ragione, non per la virgola dopo ma tra le parole sì

2024-07-31 19:28 UTC, Cadienvan commented on docs/it/la-formazione-per-autodidatti.md
> +Meglio ancora: dovreste poter guardare il codice –sempre con gli occhi della mente-, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì,
```suggestion
Meglio ancora: dovreste poter guardare il codice sempre in questo modo, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì, questo codice fa questa cosa ma si può fare meglio/più rapidamente/con meno dispendio di energie e risorse se facessi in quest’altro modo…_
```

2024-07-31 19:28 UTC, Cadienvan commented on docs/it/la-formazione-per-autodidatti.md
> +Meglio ancora: dovreste poter guardare il codice –sempre con gli occhi della mente-, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì,
@AngeloAvv che ne dici?

2024-07-31 19:32 UTC, Cadienvan commented
@AngeloAvv ho fatto degli aggiustamenti su quel bel miracolo tecnologico che è Word. Dovrei aver fixato tutto, attendo conferma sul wording e poi richiedo review a tutti!

2024-08-01 08:07 UTC, nicolaerario submitted a review, later dismissed

2024-08-01 20:33 UTC, AngeloAvv submitted a review, later dismissed

2024-08-02 07:09 UTC, Cadienvan commented on docs/it/la-formazione-per-autodidatti.md
> +Meglio ancora: dovreste poter guardare il codice - sempre con gli occhi della mente -, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì
```suggestion
Meglio ancora: dovreste poter guardare il codice sempre in questo modo, e dovreste essere in grado di immaginare scenari diversi, dovreste sentire una voce interna che vi dice: _Ah, sì, questo codice fa questa cosa ma si può fare meglio/più rapidamente/con meno dispendio di energie e risorse se facessi in quest'altro modo..._
```

2024-08-02 07:09 UTC, Cadienvan approved these changes

2024-08-02 07:16 UTC, AngeloAvv submitted a review, later dismissed

2024-08-02 09:42 UTC, nicolaerario approved these changes

2024-09-09 12:57 UTC, ugho16 submitted a review, later dismissed

2024-09-16 19:17 UTC, BrianAtzori submitted a review, later dismissed

2024-09-16 20:01 UTC, Mik23mik approved these changes

2024-09-16 20:03 UTC, Cadienvan commented
E con 6 approvazioni ci portiamo a casa un altro fantastico capitolo!

2024-09-16 20:03 UTC, merged