Add/università vs self made
Il-Libro-Open-Source/book pull request #187
Opened 2023-12-23 14:20 UTC by Cadienvan

Questo capitolo è stato inizialmente scritto da [ChristianF11](https://github.com/Il-Libro-Open-Source/book/commits?author=ChristianF11) come parte del capitolo sulla formazione, ma mi sembrava interessante proporlo, anche solo momentaneamente, come capitolo separato mentre la formazione viene portata avanti da altre persone.

Sicuro c'è da rivedere la stesura perché non rispetta propriamente le nostre guidelines, la apro in Draft per il momento.

2024-02-17 10:04 UTC, Cadienvan commented on docs/it/università-vs-self-made.md
> +A proposito di prime esperienze a livello aziendale, ti invito a leggere l'apposito capitolo “Carriera - Junior” in cui il tema viene trattato in modo più approfondito e sicuramente più stimolante.
```suggestion
```

2024-02-17 10:05 UTC, Cadienvan commented
Credo valga la pena portare dentro questo contenuto come parte del macro-capitolo che sta diventando la formazione, quindi lo tolgo dal Draft e chiedo una review formale.

2024-02-18 16:59 UTC, ugho16 commented on docs/it/università-vs-self-made.md
> +Innanzitutto come già citato è un corso molto breve (2 anni), a numero chiuso (quindi con un test di ammissione) e alla portata di tutti dal punto di vista economico, dal momento che l’iscrizione è g
```suggestion
Innanzitutto come già citato è un corso molto breve (2 anni), a numero chiuso (quindi con un test di ammissione) e alla portata di tutti dal punto di vista economico, dal momento che l’iscrizione è gratuita o a costo molto ridotto. Solitamente viene fornito un PC da poter utilizzare durante le lezioni e dedicato completamente alla programmazione, ma soprattutto, ciò che contraddistingue l’ITS (e il motivo per cui viene citato in questo capitolo) è la sua **dualità tra lezioni in aula e stage in azienda** per poter testare in modo pratico “sul campo” i concetti appresi.
```

2024-02-20 09:44 UTC, BrianAtzori submitted a review, later dismissed
Metto in approve perché per me é tutto ok, un'aggiunta che farei magari é un collegamento, tipo una sorta di approfondimento, al capitolo sulla formazione che mi sembra abbastanza collegato all'argomento e viceversa, qualcosa come "Leggi anche..."o simili, ma é solo un suggerimento

2024-02-24 09:37 UTC, Cadienvan commented
Ciao @BrianAtzori , credo che in un modo o nell'altro accorperemo il tutto in un macro capitolo di formazione, ha molto senso, per ora però come sai stiamo pubblicando separatamente i frammenti ,un indice arriverà un po' più avanti!

2024-03-05 07:37 UTC, corradopetrelli submitted a review, later dismissed

2024-03-25 22:47 UTC, ugho16 approved these changes

2024-03-31 09:43 UTC, AngeloAvv requested changes

2024-03-31 09:43 UTC, AngeloAvv commented on docs/it/università-vs-self-made.md
> +  Inoltre c’è da menzionare che in alcuni ITS viene inoltre offerta la possibilità di prepararsi e sostenere esami per certificazioni esterne quali: [CISCO IT Essentials](https://www.netacad.com/cour
Doppia ripetizione
```suggestion
  Inoltre c’è da menzionare che in alcuni ITS viene offerta la possibilità di prepararsi e sostenere esami per certificazioni esterne quali: [CISCO IT Essentials](https://www.netacad.com/courses/os-it/it-essentials), [ECDL](https://www.aicanet.it/aica/qualita/ecdl-full-standard) e [PET/FIRST/ecc.](https://www.cambridgeenglish.org/exams-and-tests/) per citarne solo alcune.
```

2024-03-31 09:43 UTC, AngeloAvv commented on docs/it/università-vs-self-made.md
> +Prima di darti la risposta a questa domanda, tengo a precisare che gli ITS in Italia offrono una vasta gamma di corsi dedicati a settori diversi, tra cui tecnologia, industria, e servizi. Per ovvi mo
Così sembra meno un parere personale

```suggestion
Prima di rispondere a questa domanda, è bene precisare che gli ITS in Italia offrono una vasta gamma di corsi dedicati a settori diversi, tra cui tecnologia, industria, e servizi. Per ovvi motivi in questo libro, più precisamente in questo capitolo, si parlerà di quelli legati al settore IT.
```

2024-03-31 09:43 UTC, AngeloAvv commented on docs/it/università-vs-self-made.md
> +L'importante è alimentare sempre questo “fuoco”, questa sete di conoscenza, che oltre ad essere fondamentale in questo settore (perché non si smette mai di imparare nel mondo IT 🤓) ci aiuterà a cresc
Mi sembrava un po' troppo arzigogolata

```suggestion
L'importante è alimentare sempre questo “fuoco”, questa sete di conoscenza, che oltre ad essere fondamentale in questo settore (perché non si smette mai di imparare nel mondo IT 🤓) ci aiuterà a crescere come figura professionale e a farci notare da aziende dove è più facile fare esperienza e assimilare concetti nuovi.
```

2024-04-01 11:33 UTC, Cadienvan commented
Grazie @AngeloAvv , mi tornavano tutti e 3 i suggerimenti!

2024-04-01 11:42 UTC, AngeloAvv submitted a review, later dismissed

2024-04-04 20:30 UTC, ugho16 submitted a review, later dismissed

2024-04-11 19:45 UTC, BrianAtzori submitted a review, later dismissed

2024-06-03 11:33 UTC, serenasensini reviewed
Capitolo sicuramente da ampliare, ma con una buona base! 🔥

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +Nel momento in cui si vuole intraprendere la via della “specializzazione” da developer, una volta concluse le scuole superiori, spesso ci si trova davanti a quello che è un bivio: _Intraprendere la v
```suggestion
Nel momento in cui si vuole intraprendere la via della “specializzazione” da developer, una volta concluse le scuole superiori, spesso ci si trova davanti a quello che è un bivio: _intraprendere la via dell’Università o iniziare un percorso di autoformazione?_
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +La risposta non è sempre così scontata, vista anche la soggettività del tema. Nel primo caso stiamo parlando di un percorso che dura minimo tre anni (o cinque, a seconda dell’obiettivo), strutturato
```suggestion
La risposta non è sempre così scontata, vista anche la soggettività del tema. Nel primo caso stiamo parlando di un percorso che dura minimo tre anni (o cinque, a seconda dell’obiettivo), strutturato e tenuto da docenti formati e che seguono un piano di studi ben preciso, mentre nel secondo abbiamo una durata potenzialmente ignota e che si basa esclusivamente sulla nostra organizzazione, disciplina e motivazione.
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +In molti però non sono a conoscenza di una terza via, ovvero degli [ITS (_Istituto Tecnico Superiore_)](https://www.miur.gov.it/web/guest/tematica-its) di programmazione, degli enti solitamente finan
```suggestion
Molte persone però non sono a conoscenza di una terza via, ovvero degli [ITS (_Istituto Tecnico Superiore_)](https://www.miur.gov.it/web/guest/tematica-its) di programmazione, degli enti solitamente finanziati dalla regione e/o da alcune aziende del settore, il cui scopo è quello di formare nel giro di un paio d’anni delle figure professionali da inserire nel mondo dell’IT.
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +**_“Come è strutturato il percorso formativo di un ITS?”_**
```suggestion
**_“Com'è strutturato il percorso formativo di un ITS?”_**
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +- **Primo Anno**: Prevalentemente dedicato alle **lezioni in aula**, dove avrai l'opportunità di apprendere dalle competenze di **docenti aziendali**<sup>1</sup> e universitari, i concetti, i linguag
```suggestion
- **Primo Anno**: Prevalentemente dedicato alle **lezioni in aula**, dove si ha l'opportunità di apprendere dalle competenze di **docenti aziendali**<sup>1</sup> e universitari, i concetti, i linguaggi e gli strumenti fondamentali della figura professionale a cui è dedicato il corso.
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +- **Secondo Anno**: Dopo una breve fase di lezioni dedicate agli ultimi moduli, mirate a esplorare concetti più avanzati, come l'_Architettura del Software_ per esempio, l'attenzione si sposterà prin
```suggestion
- **Secondo Anno**: Dopo una breve fase di lezioni dedicate agli ultimi moduli, mirate a esplorare concetti più avanzati, come l'_Architettura del Software_ per esempio, l'attenzione si sposta principalmente sullo **stage lavorativo**, nonché ultima attività prima dell’esame finale (necessario per conseguire un _Diploma di [V livello EQF](https://europa.eu/europass/it/description-eight-eqf-levels)_).
```

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +È vero, sicuramente la preparazione concettuale risulterà meno solida di quella universitaria, ma è proprio qua che deve subentrare la nostra proattività e la nostra curiosità!
Non credo sia questione di solidità, ma piuttosto di preparazione verso il mondo del lavoro!

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +Nel momento in cui si vuole intraprendere la via della “specializzazione” da developer, una volta concluse le scuole superiori, spesso ci si trova davanti a quello che è un bivio: _Intraprendere la v
Avrei comunque approfondito il tema "università" e "auto-formazione", per dare modo di misurarsi con tutte le realtà!

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +“_Si conclude il modulo di lezioni su Python e vorrei saperne ancora di più. Ottimo! Partendo da questa infarinatura posso apprendere più facilmente anche in maniera autonoma._”
Non ho compreso il senso della frase nel contesto attuale.. forse era un esempio di stereotipi nel settore?

2024-06-03 11:33 UTC, serenasensini commented on docs/it/università-vs-self-made.md
> +“_Mi trovo a fare uno stage in un’azienda che usa VUE.js? Conosco JavaScript ma non avevo mai considerato questo Framework. Ecco un’ottima opportunità per farlo ora_”.
Come sopra. Forse aggiungerei una riga o due per dare un filo logico ai paragrafi prima e dopo

2024-06-03 11:43 UTC, Cadienvan commented
@ChristianF11 lascio a te l'onere di portare avanti commentando o accettando le modifiche. Avendo aperto io la PR metti anche solo un pollice su alle modifiche che reputi coerenti e io le porto dentro!

2024-06-03 17:47 UTC, ChristianF11 commented on docs/it/università-vs-self-made.md
> +Nel momento in cui si vuole intraprendere la via della “specializzazione” da developer, una volta concluse le scuole superiori, spesso ci si trova davanti a quello che è un bivio: _Intraprendere la v
Sono d'accordo, ma pensavo di lasciare spazio a qualcun'altro su questi due argomenti, siccome non saprei come approfondirli onestamente

2024-06-03 17:48 UTC, ChristianF11 commented on docs/it/università-vs-self-made.md
> +“_Si conclude il modulo di lezioni su Python e vorrei saperne ancora di più. Ottimo! Partendo da questa infarinatura posso apprendere più facilmente anche in maniera autonoma._”
Ho scritto questa frase basandomi su diverse testimonianze di colleghi e non. Alcuni si sono laureati mentre altri hanno svolto un corso più simile all'ITS e parlandoci mi è sembrato emergere questo aspetto, ovvero che il corso post-diploma è molto più mirato al mondo lavorativo tralasciando alcuni concetti teorici che invece si trattano all'università

2024-06-03 17:54 UTC, ChristianF11 commented
@Cadienvan ho lasciato il pollice in su per le modifiche di correzione del testo già presente. Per le ultime, che riguardano l'aggiunta l'aggiunta di testo io avrei delle modifiche da rilasciare. Scusa la domanda banale, ma queste le posso pushare e in automatico vengono riportate qua o devo fare altro?

2024-06-03 20:01 UTC, Cadienvan commented
@ChristianF11 credo che la cosa migliore sia che tu faccia un fork di main e che faccia copia e incolla del contenuto di questo capitolo, dopodiché puoi aprire una PR ed essere indipendente. Quando hai fatto lo scrivi qui e io chiudo questa PR.

Inizialmente eravamo partiti con "L'Ambassador apre la PR" ma effettivamente questo toglie libertà e indipendenza a chi stende il contenuto!

2024-06-25 19:28 UTC, Cadienvan commented
Ciao @ChristianF11 se hai difficoltà con il fork scrivimi pure su LinkedIn che ti supporto!

2024-06-27 19:40 UTC, Cadienvan commented
Sposto in draft il capitolo per permettere a Christian di prenderne il contenuto quando riuscirà, aprendo apposita PR, ci siamo sentiti LinkedIn e ad ora il tempo per farlo non basta!

2024-07-09 12:05 UTC, Cadienvan commented
Chiudo in quanto _superseeded_ dalla #239

2024-07-09 12:05 UTC, closed without merging