feat: aggiunto matomo tracking
Il-Libro-Open-Source/book pull request #192
Opened 2024-01-04 14:40 UTC by Cadienvan

2024-01-04 14:52 UTC, Cadienvan commented
@Il-Libro-Open-Source/tech-group con @devnuli abbiamo configurato Matomo e l'abbiamo fatto girare.
Per verificarlo ho girato il branch di deploy su feat/matomo e l'ho eseguito.

Il problema, chiaramente, è che ci perdiamo il concetto del markdown e dobbiamo tramutare tutto in HTML.
Ho poca competenza sul mondo GIthub Pages per sapere come muovermi quindi attendo vostre indicazioni e, se posso, aiuto.

2024-01-04 15:46 UTC, elgorditosalsero commented
@Cadienvan qual è il problema? 😄 

Matomo ha bisogno di aggiungere qualcosa ad ogni pagina?

2024-01-04 15:49 UTC, Cadienvan commented
@elgorditosalsero Il punto è che se l'index è in HTML, Github smette di renderizzare il markdown e lo mostra come raw.
Credo quindi sia necessario prevedere un build step di qualche tipo, o magari basta una config ma non avendolo mai fatto non saprei.

2024-01-04 15:49 UTC, Cadienvan commented
Poi, sì, avrebbe senso inserire Matomo in ogni pagina..

2024-01-04 16:00 UTC, elgorditosalsero commented
> @elgorditosalsero Il punto è che se l'index è in HTML, Github smette di renderizzare il markdown e lo mostra come raw. Credo quindi sia necessario prevedere un build step di qualche tipo, o magari basta una config ma non avendolo mai fatto non saprei.

La scelta più semplice e veloce è scegliere uno di questi temi, in base al tema settare nel layout di default il codice di Matomo, che così sarà in tutte le pagine che usano quel layout

In questo modo i file rimangono `.md` e non dobbiamo avere step aggiuntivi

2024-01-04 16:01 UTC, elgorditosalsero commented
O comunque altri temi `jellyk` presenti su GH

2024-01-04 16:19 UTC, Cadienvan commented
Claro!
@elgorditosalsero che ne dici di proporre una PR con il minimal jekyll impostato e Matomo già inserito? Così facendo posso girare il deploy sul branch della PR, lanciarlo, fare due screen, proporlo a tutti e ripristinare.

Credi di riuscire a metterci mano tu con i ragazzi del tech? Niente fretta, è che io avrò due weekend occupati, altrimenti fo' io!

2024-01-22 13:36 UTC, elgorditosalsero submitted a review, later dismissed
So bravo e bello

2024-01-22 13:40 UTC, corradopetrelli requested changes

2024-01-22 13:40 UTC, corradopetrelli commented on _config.yml
> +footer_content: "Copyright &copy; 2023-2023 Il Libro Open Source"
```suggestion
footer_content: "Copyright &copy; 2023-2024 Il Libro Open Source"
```

2024-01-22 13:43 UTC, merged