feat: aggiunta capitolo community e networking
Il-Libro-Open-Source/book pull request #195
Opened 2024-01-13 10:41 UTC by Cadienvan

Con @davideimola ci siamo presi carico di questo capitolo.

Comincio a buttare giù una prima versione, Davide, fammi sapere, così poi chiediamo una review!

2024-01-18 12:08 UTC, davideimola reviewed
Devo vedere ancora la parte di Networking! Ma queste sono delle hint che mi vengono :)

2024-01-18 12:08 UTC, davideimola commented on docs/it/community-e-networking.md
> +Partecipare alle community è fondamentale per chiunque voglia intraprendere la carriera di sviluppatore. Le community sono un luogo dove poter imparare, confrontarsi e crescere, ma anche un luogo dov
```suggestion
Consideriamo la partecipazione alle community fondamentale, ma non obbligatoria, per chiunque voglia intraprendere la carriera di sviluppatore. Le community come detto sono un luogo di crescita personale e professionale, permettono inoltre di fare networking e ampliare la propria cerchia di conoscenze e amicizie, le quali potrebbero aiutarvi ad aprirvi molte possibilità future.

Le community inoltre sono uno dei migliori modi per imparare qualcosa di nuovo, perché tendenzialmente in queste avviene uno scambio di conoscenze gratuite tra i vari membri! Quello che potreste apprendere un giorno, potreste insegnarlo ad altri!

Ovviamente tra i pro non possiamo non citare il divertimento, le community sono luoghi di ritrovo di persone con uguali interessi, quindi potrebbe essere più facile per una persona creare un legame con queste.
```

2024-01-18 12:08 UTC, davideimola commented on docs/it/community-e-networking.md
> +Spesso si dice che il modo migliore per imparare qualcosa è insegnarla agli altri e partecipare alle community ci permette di mettere in pratica le nostre conoscenze e di imparare cose nuove.
```suggestion
```

2024-01-18 12:08 UTC, davideimola commented on docs/it/community-e-networking.md
> +Partecipare alle community è molto semplice. Esistono community online e offline, quindi possiamo scegliere quella che più ci si addice. Le community online sono molto più facili da raggiungere, ma q
```suggestion
Partecipare alle community è molto semplice. Esistono community online e offline, quindi possiamo scegliere quella che più ci si addice. Le community online sono molto più facili da raggiungere, ma quelle offline sono molto più ricche dal punto di vista del networking. Per non fare torti a nessuno, in questo capitolo non citeremo alcuna community in particolare, ma ci limiteremo a dire che molte di queste community sono raggiungibili tramite i social network, come Facebook, Twitter, Instagram, LinkedIn, Telegram, Discord, Slack, ecc. e molte delle persone più attive sui social fanno parte di diverse community, quindi spesso sarà sufficiente seguire queste per entrare a far parte del loro mondo.
```

2024-01-18 12:08 UTC, davideimola commented on docs/it/community-e-networking.md
> +- **Stabilisci delle regole**: Se vogliamo creare una community, dobbiamo stabilire delle regole che permettano alle persone di interagire in maniera civile e rispettosa. Questo aspetto risulta sempr
```suggestion
- **Stabilisci delle regole**: Se vogliamo creare una community, dobbiamo stabilire delle regole che permettano alle persone di interagire in maniera civile e rispettosa. Questo aspetto risulta sempre più importante con l'aumentare del numero di persone che partecipano alla community.
- **Non demoralizzarti**: Se ci tieni veramente alla tua community non demoralizzarti se questa non diventa popolare. Capiamo che può essere bello, ma non è fondamentale! Anche la community più piccola, può magari essere più attiva di una enorme e può portare dei benefici ai suoi membri!
```

2024-01-18 14:09 UTC, davideimola commented on docs/it/community-e-networking.md
> +Il networking è un aspetto fondamentale per chiunque voglia intraprendere la carriera di sviluppatore. Per networking intendiamo la capacità di creare e mantenere relazioni con altre persone, in part
```suggestion
Con networking intendiamo la capacità di creare e mantenere relazioni con altre persone, in particolare con altre persone che lavorano nel nostro stesso settore o condividono i nostri stessi interessi.
```

2024-01-18 14:11 UTC, davideimola commented on docs/it/community-e-networking.md
> +Il networking è fondamentale per chiunque voglia intraprendere la carriera di sviluppatore, ma è particolarmente importante per chi è all'inizio. Quando si è agli inizi, infatti, non si ha ancora un
```suggestion
Il networking è importante per chiunque voglia intraprendere la carriera di sviluppatore, ma è particolarmente cruciale per chi è all'inizio. Non avendo ancora un curriculum da poter mostrare e non si hanno ancora le competenze necessarie per poter essere assunti, risultano fondamentali le connessioni che si creano per poter trovare le prime opportunità. Quando si è agli inizi, inoltre si ha ancora la possibilità di scegliere il proprio percorso e il networking è fondamentale per poter apprendere le varie opportunità che il mondo dello sviluppo software offre.
```

2024-01-18 14:12 UTC, davideimola commented on docs/it/community-e-networking.md
> +Non puoi mai sapere se la persona seduta accanto a te in un meetup o in una conferenza potrebbe essere il tuo prossimo datore di lavoro o il tuo prossimo cliente, o più semplicemente un futuro colleg
```suggestion
Partecipando a una community non puoi mai sapere se una determinata persona potrebbe diventare il tuo prossimo datore di lavoro o il tuo prossimo cliente, o più semplicemente un futuro collega che ti aprirà le porte di un'azienda in cui vorresti lavorare.
```

2024-01-18 14:15 UTC, davideimola commented on docs/it/community-e-networking.md
> +Fare networking può aprirti possibilità che nemmeno pensavi di avere e può aiutarti a crescere professionalmente in maniera esponenziale. Non è raro, infatti, che un dev venga assunto in un'azienda g
```suggestion
Fare networking può aprirti possibilità che nemmeno pensavi di avere e può aiutarti a crescere professionalmente in maniera esponenziale. Non è raro, infatti, che un dev venga assunto in un'azienda grazie a una conoscenza che lo ha raccomandato per una posizione o che un dev noto internamente in un'azienda venga contattato dalla stessa per una posizione che non era stata ancora pubblicizzata, aumentando così le possibilità di essere assunto.

Sicuramente tutti questi pro sono molto importanti, ma una cosa che non andrebbe mai trascurata è la bellezza di poter conoscere gente nuova e creare nuove connessioni genuine e durature.
```

2024-01-18 14:17 UTC, davideimola commented on docs/it/community-e-networking.md
> +Negli ultimi anni (Decennio 2013-2023) il networking online è diventato sempre più importante e il grosso delle opportunità da questo punto di vista si trova su LinkedIn. Questo non significa che non
```suggestion
Negli ultimi anni (Decennio 2013-2023) il networking online è diventato sempre più importante e il grosso delle opportunità da questo punto di vista si trova su LinkedIn. Questo non significa che non si possa fare networking anche su altri social network, ma LinkedIn è sicuramente il social network più utilizzato per il nostro settore.
```

2024-01-18 14:18 UTC, davideimola commented on docs/it/community-e-networking.md
> +Per fare networking su LinkedIn è necessario creare un profilo professionale, che sia in linea con il nostro settore di appartenenza e che sia aggiornato con le nostre esperienze e le nostre competen
```suggestion
Per fare networking su LinkedIn è necessario creare un profilo professionale, che sia in linea con il nostro settore di appartenenza e che sia aggiornato con le nostre esperienze e le nostre competenze. Una volta creato il profilo, sarà sufficiente iniziare a connettersi con altre persone, possibilmente con persone che potenzialmente condividano i nostri stessi interessi.
```

2024-01-18 14:19 UTC, davideimola commented on docs/it/community-e-networking.md
> +Una volta connessi, sarà possibile interagire con queste persone, commentando i loro post o inviando loro messaggi privati. Questo ci permetterà di creare una relazione con queste persone e di farci
```suggestion
Una volta connessi, sarà possibile interagire con queste persone, commentando i loro post o inviando loro messaggi privati. Questo ci permetterà di creare una relazione con loro e ci permetterà di farci conoscere. Questo è il primo passo per fare networking su LinkedIn.
```

2024-01-18 14:20 UTC, davideimola commented on docs/it/community-e-networking.md
> +Non esiste una formula magica da questo punto di vista, ma anche in questo caso, costanza e passione sono ingredienti fondamentali per intraprendere questo percorso.
```suggestion
Ovviamente, come precedentemente detto non esiste solo LinkedIn, ma anche partecipare a una community online affine può essere un ottimo modo per iniziare a crescere la propria rete di contatti.

Non esiste una formula magica da questo punto di vista, ma anche in questo caso, costanza e passione sono ingredienti fondamentali per intraprendere questo percorso.
```

2024-01-18 14:28 UTC, davideimola commented on docs/it/community-e-networking.md
> +Il networking offline è molto più difficile da intraprendere, ma è anche molto più efficace. Per fare networking offline è necessario partecipare a eventi, come meetup e conferenze, e interagire con
```suggestion
Il networking offline è molto più difficile da intraprendere, ma è anche molto più efficace. Per fare networking offline è necessario partecipare a eventi, come meetup e conferenze, e interagire con le persone che partecipano a questi eventi.

Come potresti ben capire in questo caso bisognerà essere il meno timidi possibile e di non aver timore delle altre persone! Potete anche cominciare ponendo delle domande e non pensare se e quanto possano essere stupide, nessuno nasce con tutte le risposte pronte!
```

2024-01-18 14:29 UTC, davideimola commented on docs/it/community-e-networking.md
> +In questo capitolo abbiamo visto come il networking e la partecipazione alle community siano due aspetti fondamentali per chiunque voglia intraprendere la carriera di sviluppatore. Sono due aspetti c
```suggestion
In questo capitolo abbiamo visto come il networking e la partecipazione alle community siano due aspetti fondamentali per chiunque voglia intraprendere la carriera di sviluppatore. Sono due aspetti che possono aiutarci a crescere professionalmente e che possono aprirci opportunità che altrimenti non avremmo, ma è bene ricordare che non sono _necessità_, ma _opportunità_ che abbiamo e che possiamo sfruttare per crescere sia personalmente che professionalmente.
```

2024-01-20 09:13 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +Non puoi mai sapere se la persona seduta accanto a te in un meetup o in una conferenza potrebbe essere il tuo prossimo datore di lavoro o il tuo prossimo cliente, o più semplicemente un futuro colleg
Credo che l'aspetto più "diretto" del messaggio iniziale suoni meglio

2024-01-20 09:13 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +Il ruolo del dev è cambiato molto negli ultimi anni e oggi è molto più vicino al business e alla comunicazione rispetto a quanto non fosse in passato, o perlomeno, lo è per chi vuole fare il salto di
```suggestion
Il ruolo del dev è cambiato molto negli ultimi anni e oggi è molto più vicino al business e alla comunicazione rispetto a quanto non fosse in passato, o perlomeno, lo è per chi vuole fare il salto di qualità. Questo significa che un/una dev deve essere in grado di comunicare con colleghi di altri reparti, con i clienti e con i superiori, deve essere in grado di vendere le proprie idee e di convincere gli altri a seguire le sue idee. Queste sono tutte competenze che si acquisiscono con l'esperienza, ma che possono essere affinate anche attraverso il networking e la partecipazione alle community.
```

2024-01-20 09:13 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +Il ruolo del dev è cambiato molto negli ultimi anni e oggi è molto più vicino al business e alla comunicazione rispetto a quanto non fosse in passato, o perlomeno, lo è per chi vuole fare il salto di
Fatto!

2024-01-20 09:14 UTC, Cadienvan commented
@davideimola ho portato dentro tutte le proposte tranne una, perché reputo il messaggio iniziale più efficace e diretto!

Fammi sapere quando riesci a dare un occhio alla seconda parte! ;)

2024-01-20 09:15 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +- **Non demoralizzarti**: Se ci tieni veramente alla tua community non demoralizzarti se questa non diventa popolare. Capiamo che può essere bello, ma non è fondamentale! Anche la community più picco
```suggestion
- **Non demoralizzarti**: Se ci tieni veramente alla tua community non demoralizzarti se questa non diventa popolare. Capiamo possa essere un bel traguardo, ma non è fondamentale! Anche una community più raccolta può risultare molto attiva e portare dei benefici ai suoi membri!
```

2024-02-17 10:28 UTC, akelity commented on docs/it/community-e-networking.md
> +Partecipare alle community è molto semplice. Esistono community online e offline, quindi possiamo scegliere quella che più ci si addice. Le community online sono molto più facili da raggiungere, ma q
Forse tra le piattaforme metterei anche Meetup (specificando che serve per le community offline)

2024-02-17 10:28 UTC, akelity commented on docs/it/community-e-networking.md
> +- **Non demoralizzarti**: Se ci tieni veramente alla tua community non demoralizzarti se questa non diventa popolare. Capiamo possa essere un bel traguardo, ma non è fondamentale! Anche una community
Qui aggiungerei tra i punti anche quello di "non chiudersi" ma collaborare con altre community e gruppi con lo scopo di aiutare loro a crescere e cercando di crescere tramite il loro aiuto

2024-02-17 11:31 UTC, Mik23mik commented on docs/it/community-e-networking.md
> +
Forse un po’ troppe volte ripetuta (anche se capisci che é fatto intenzionalmente) la parola community

2024-02-17 14:57 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +Partecipare alle community è molto semplice. Esistono community online e offline, quindi possiamo scegliere quella che più ci si addice. Le community online sono molto più facili da raggiungere, ma q
Makes sense.

2024-02-17 14:58 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +- **Non demoralizzarti**: Se ci tieni veramente alla tua community non demoralizzarti se questa non diventa popolare. Capiamo possa essere un bel traguardo, ma non è fondamentale! Anche una community
Ci sta!

2024-02-17 15:00 UTC, Cadienvan commented on docs/it/community-e-networking.md
> +
Ciao @Mik23mik , ho rivisto il paragrafo, spero suoni meglio!

2024-02-17 15:00 UTC, Cadienvan commented
@Mik23mik @akelity ho portato dentro i vostri suggerimenti, fatemi sapere!

2024-02-17 15:19 UTC, akelity submitted a review, later dismissed
LGTM

2024-02-18 09:16 UTC, AngeloAvv requested changes
Tutto sommato fila liscio, ottimo capitolo!
Ho segnalato giusto qualcosina da sistemare qua e la

2024-02-18 09:16 UTC, AngeloAvv commented on docs/it/community-e-networking.md
> +Detto questo, è vero che lo sviluppo software è un lavoro che richiede molta concentrazione e che spesso si lavora in solitudine, il che può portare a una certa tendenza all'isolamento. Soprattutto n
Che ne direste di rielaborare? Potrebbe passare l'idea che si debba entrare in "monk mode" durante i primi dieci anni di carriera.

```suggestion
Detto questo, è vero che lo sviluppo software è un lavoro che richiede molta concentrazione e che spesso si lavora in solitudine, il che può portare a una certa tendenza all'isolamento. Agli albori dell'informatica, quando non esistevano ancora i social network e le community online, era molto più facile per chi facesse questo lavoro isolarsi, il che ha portato alla nascita di una percezione così radicata che spesso anche chi fa parte del settore si stupisce di quante community esistano e di quanto sia facile fare networking.
```

2024-02-18 09:16 UTC, AngeloAvv commented on docs/it/community-e-networking.md
> +- **Sii inclusivo**: Le community sono fatte di persone e le persone sono fatte di differenze. Se vogliamo creare una community, dobbiamo essere inclusivi e accettare le differenze. Non possiamo pens
```suggestion
- **Sii inclusivo**: Le community sono fatte di persone e ogni persona è diversa dall'altra. Se vogliamo creare una community, dobbiamo essere inclusivi e accettare le diversità. Non possiamo pensare di creare una community se non siamo disposti ad accettare questo.
```

2024-02-18 09:16 UTC, AngeloAvv commented on docs/it/community-e-networking.md
> +- **Non chiudersi**: Il mondo delle community è fatto anche di collaborazione tra le stesse. Spesso, infatti, le community si aiutano a vicenda e si supportano, anche solo facendosi pubblicità a vice
```suggestion
- **Essere aperti**: Il mondo delle community è fatto anche di collaborazione tra le stesse. Spesso, infatti, le community si aiutano a vicenda e si supportano, anche solo facendosi pubblicità a vicenda o scambiandosi consigli e risorse. Non chiudersi in se stessi e cercare di collaborare con altre community può portare a risultati inaspettati.
```

2024-02-18 09:16 UTC, AngeloAvv commented on docs/it/community-e-networking.md
> +Vuoi un esempio pratico del potere del networking? Questo capitolo fa parte di un libro scritto da una community di persone che condivide la passione per l'Open Source, e la prima stesura è stata fat
Typo
```suggestion
Vuoi un esempio pratico del potere del networking? Questo capitolo fa parte di un libro scritto da una community di persone che condivide la passione per l'Open Source, e la prima stesura è stata fatta da due persone che si sono conosciute grazie ad un'amicizia in comune, a sua volta dev, che ci ha presentati e ci ha permesso di conoscerci. A distanza di parecchi mesi da quel primo contatto, abbiamo deciso di scrivere questo capitolo insieme dopo esserci visti ad un paio di conferenze, a dimostrazione di quanto il networking sia imprevedibile quanto efficace.
```

2024-02-18 17:10 UTC, ugho16 approved these changes

2024-02-19 10:34 UTC, GuidoPenta approved these changes
me gusta!

2024-02-23 20:09 UTC, merged