Aggiunta sezione Tools e modificato sezione 'tecniche dei test'
Il-Libro-Open-Source/book pull request #197
Opened 2024-01-19 10:40 UTC by mariomontella

Piccola prima modifica. Aggiornatemi!

2024-01-20 09:24 UTC, Cadienvan commented on docs/it/testing.md
> +- **Grey-box testing**: Il test _grey-box_ è una tecnica di test in cui il tester ha conoscenza parziale dell'implementazione del sistema. Questo tipo di testing è particolarmente utile quando si des
```suggestion
- **Grey-box testing**: Il test _grey-box_ è una tecnica di test in cui il tester ha conoscenza parziale dell'implementazione del sistema. Questo tipo di testing è particolarmente utile quando si desidera testare il software da una prospettiva esterna, ma con una comprensione sufficiente della sua architettura interna per creare test più mirati ed efficaci. I tester hanno accesso limitato al codice sorgente e alla struttura interna, permettendo loro di comprendere alcuni aspetti dell'architettura del software senza una conoscenza dettagliata. Il _grey-box_ testing si concentra sulle interfaccie e le API del sistema, testando la comunicazione e l'interazione tra diverse unità o moduli. Il vantaggio principale riguarda la maggiore efficienza, data la combinazione di conoscenze interne ed esterne, permettendo di creare test più mirati, aumentando l'efficienza del processo di testing.
```

2024-01-20 09:25 UTC, Cadienvan commented on docs/it/testing.md
> +#### Tools e Frameworks per il Testing
```suggestion
## Tools e Frameworks per il Testing
```

2024-01-20 09:25 UTC, Cadienvan commented on docs/it/testing.md
> +Ora che abbiamo esplorato i vari tipi di test e le loro applications, è di fondamentale importanza conoscere gli strumenti e i frameworks che possono rendere questi processi più efficienti ed efficac
```suggestion
Ora che abbiamo esplorato i vari tipi di test e le loro applicazioni, è di fondamentale importanza conoscere gli strumenti e i framework che possono rendere questi processi più efficienti ed efficaci. Ogni tipologia di test può essere supportata e migliorata dall'uso di tool specifici, che aiutano l'automazione dei test stessi, rendendo più semplice la scrittura del codice di test e fornendo feedback più dettagliati sui risultati.
```

2024-01-20 09:29 UTC, Cadienvan requested changes
Mi piace molto l'accrescimento che hai dato alle varie aree del capitolo, veramente un lavoro ben fatto!

Mi sono permesso di suggerire qualche aggiustamento di forma e ho aggiunto un "disclaimer" agli strumenti di testing non volendo rischiare di far passare il messaggio sbagliato. Se ti torna, facciamo fare una review anche al resto del team Ambassador!

2024-01-20 09:31 UTC, mariomontella commented
Sisi va benissimo. Ho visto le modifiche. Tranquillo errori miei ahahah

2024-01-20 09:54 UTC, Cadienvan commented
Ciao @mariomontella ,
come d'accordo ho apportato le modifiche, attendo solo il lancio del formatter così poi chiediamo la review!

2024-01-20 10:40 UTC, Cadienvan commented
@Il-Libro-Open-Source/tech-group c'è anche Prettier aggiornato ma lo vedo come un non problema, che ne pensate?

2024-01-20 10:40 UTC, Cadienvan approved these changes

2024-01-20 10:58 UTC, EMCestari commented on docs/it/testing.md
> +- **Black-box testing**: Il test _black-box_ è una tecnica di test in cui il tester non ha conoscenza dell'implementazione del sistema. Il focus è sull'esaminazione del funzionamento dell'applicazion
Qui attenzione a "indipendentemente", è scritta con un typo

2024-01-20 11:02 UTC, EMCestari commented on docs/it/testing.md
> + - **TestNG(Java)**: Fornisce funzionalità avanzate per i test d'integrazione. inclusa l'esecuzione parallela dei test e la gestione delle dipendeze.
Attenzione alla maiuscola dopo il punto: "Inclusa"

2024-01-20 11:02 UTC, EMCestari commented on docs/it/testing.md
> + - **TestNG(Java)**: Fornisce funzionalità avanzate per i test d'integrazione. inclusa l'esecuzione parallela dei test e la gestione delle dipendeze.
Attenzione anche a typo "dipendeze"

2024-01-20 11:02 UTC, EMCestari approved these changes
Approvato con commenti per typo minori

2024-01-20 13:06 UTC, mariomontella commented on docs/it/testing.md
> +- **Black-box testing**: Il test _black-box_ è una tecnica di test in cui il tester non ha conoscenza dell'implementazione del sistema. Il focus è sull'esaminazione del funzionamento dell'applicazion
risolto, sorry. Errori di distrazione

2024-01-20 13:34 UTC, Cadienvan approved these changes

2024-01-20 15:22 UTC, EMCestari submitted a review, later dismissed

2024-01-22 14:14 UTC, corradopetrelli approved these changes

2024-01-23 08:26 UTC, allevo reviewed
Ciao! mi sembra tutto ok.
L'unica cosa che mi viene in mente di sottolineare sono i tool di test non agnostici dal linguaggio poiché mi chiedo se non vale la pena coordinare l'intero libro sulla scelta di questi 2 linguaggi come esempi in modo da non averne di diversi nei capitoli, che potrebbe confondere il lettore.

2024-01-24 14:22 UTC, BrianAtzori approved these changes
Ciao, per me le aggiunte sono ok, non ho trovato errori e concenttualmente mi sembra tutto ok

2024-01-25 20:35 UTC, sensorario commented on docs/it/testing.md
> +- **White-box testing**: Il test _white-box_ è una tecnica di test in cui il tester ha conoscenza dell'implementazione del sistema, quindi dell'intero codice sorgente. Questo approccio si concentra s
```suggestion
- **White-box testing**: Il test _white-box_ è una tecnica di test in cui il tester ha conoscenza dell'implementazione del sistema, quindi dell'intero codice sorgente. Questo approccio si concentra sull'esaminare il comportamento interno del software e sul garantire che tutte le vie logiche ed i segmenti di codice siano testati. Il test ha un focus sulla validazione dei percorsi di esecuzione all'interno del codice, assicurando che tutte le condizioni, i cicli ed i percorsi di codice siano testati. Questo metodo è efficace nell'individuare bug specifici nel codice, come errori di logica, infinity loop e istruzioni non raggiunte.
```

2024-01-25 20:36 UTC, sensorario approved these changes

2024-01-27 09:04 UTC, merged