Aggiunge Mutation al capitolo sul testing
Il-Libro-Open-Source/book pull request #215
Opened 2024-02-12 13:14 UTC by Cadienvan

Come da titolo, ho aggiunto il mutation testing che spesso viene trascurato quando si parla del mondo dei test.

2024-02-12 19:52 UTC, corradopetrelli approved these changes

2024-02-12 20:57 UTC, AngeloAvv submitted a review, later dismissed
Sembra la trama di un film sci-fi

2024-02-13 09:27 UTC, allevo reviewed
Varrebbe la pena aggiungere una nota per cui lo score non ha senso che sia al 100%?
Avrebbe senso dare un numero indicativo dello score?

2024-02-13 09:27 UTC, allevo commented on docs/it/testing.md
> +Il mutation testing è una metodologia di test in cui il codice sorgente viene modificato in modo da introdurre volutamente degli errori. Questi errori vengono chiamati _mutanti_. L'obiettivo del muta
Considerazioni:
- la parola "mutanti" potrebbe non essere corretta in questo caso: il codice subisce delle mutazioni (introduzione degli errori). Il "mutante" è la versione mutata, non gli errori intromessi.
- ho messo all'inizio il motivo del mutation test in modo da rendere chiaro il motivo per cui esistono.


```suggestion
Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice, si creano diverse versioni diverse, ognuna delle quali introduce una mutazione, piccola a piacere. Queste versioni mutate vengono chiamati _mutanti_. L'obiettivo del mutation testing è di verificare se la test suite identifica la mutazione: se un mutante non viene rilevato da un test, viene considerato _vivo_ e i test a riguardo vengono considerati non sufficienti per quella mutazione. Se un mutante viene rilevato da un test, viene considerato _morto_ e i test a riguardo vengono considerati sufficienti per quel mutante.
```

2024-02-13 09:27 UTC, allevo commented on docs/it/testing.md
> +Applicando la formula `mutation score = (mutanti uccisi / mutanti totali) * 100`, possiamo ottenere una percentuale di mutanti uccisi, che ci permette di capire quanto il nostro codice sia realmente
la parola "uccisi" non è stata usata nel paragrafo precedente che fa riferimento invece a mutanti "morti". Ho usato la stessa nomenclatura anche qui.

```suggestion
Applicando la formula `mutation score = (mutanti morti / mutanti totali) * 100`, possiamo ottenere una percentuale di mutanti morti, che ci permette di capire quanto il nostro codice sia realmente testato.
```

2024-02-13 09:27 UTC, allevo commented on docs/it/testing.md
> +- Condizioni (cambiare un "==" con un "!=")
```suggestion
- Comparazioni (cambiare un "==" con un "!=")
```
In teoria, un mutation framework può cambiare anche solo un ">=" in ">".

2024-02-13 09:36 UTC, Cadienvan commented
Ciao @allevo ,
tutte giuste le osservazioni fatte, le ho portate dentro!

Riguardo al "100%".. Magari una aggiunta alla sezione sotto, "Test Coverage", in cui diciamo che anche per il mutation non necessariamente serve averlo al 100%?

2024-02-13 12:31 UTC, allevo commented
@Cadienvan il test coverage non fa parte dei mutation tests. Il code coverage indica per quale riga passa quale test. Qui è "il contrario": quale test si rompe per quale riga. Secondo me crea confusione nel lettore mettere tutto assieme.

2024-02-17 10:33 UTC, Cadienvan commented
Ok @allevo , sì, mi torna!

Hai una idea per buttarlo giù?

2024-02-19 08:30 UTC, allevo commented on docs/it/testing.md
> +
Ho invertito i 2 paragrafi in modo da dedicare la fine di questo paragrafo allo score.

```suggestion
Le mutazioni possono essere effettuate su vari aspetti del proprio software:
- Operazioni (cambiare un "-" con un "+")
- Comparazioni (cambiare un "==" con un "!=")
- Istruzioni (eliminare delle righe di codice)
- Valori (cambiare il _return_ di una funzione)

Applicando la formula `mutation score = (mutanti morti / mutanti totali) * 100`, possiamo ottenere una percentuale di mutanti morti, che ci permette di capire quanto il nostro codice sia realmente testato.

Vista la natura dei mutation test, il numero di mutazioni può essere molto alto e non sempre le mutazioni coinvolgono i principali use case. Per questo non bisogna stupirsi che lo score sia basso. Infatti uno score alto significa che esiste un test per ogni condizione all'interno del proprio codice, il che porterebbe a:
- un aumento del tempo per la scrittura del codice di test
- un aumento del costo di mantenimento/aggiornamento del codice di test
In base alle esigenze di progetto, il team può decidere se implementare e migliorare il `mutation score`.

Pur essendo un'ottimo strumento per misurare la qualità della test suite, in molti casi questa tecnica di testing non è usata per via della sua complessità e costo di implementazione.
```

2024-02-20 08:49 UTC, guizzo commented on docs/it/testing.md
> +Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice, si creano diverse versioni diverse, ognuna delle quali introduce una mutazione, piccola a piacere
@Cadienvan _...si creano *diverse* versioni *diverse*_ questo passaggio mi disturba molto... non suona male anche a te?

2024-02-20 09:34 UTC, BrianAtzori requested changes
Come sezione é ok e a parte l'introduzione che é da rivedere forse, mi sembra che arrivi in modo chiaro il concetto da esprimere 😊

2024-02-20 09:34 UTC, BrianAtzori commented on docs/it/testing.md
> +Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice, si creano diverse versioni diverse, ognuna delle quali introduce una mutazione, piccola a piacere
Mi aggancio a @guizzo per dire che questa sezione forse é da rivedere, l'argomento é un filo complesso e forse tra ripetizioni e forma, i concetti non arrivano in modo efficace infatti ho dovuto rileggerla un paio di volte, andrebbe solo rivista la struttura della frase a mio avviso

2024-02-24 09:52 UTC, Cadienvan commented on docs/it/testing.md
> +Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice, si creano diverse versioni diverse, ognuna delle quali introduce una mutazione, piccola a piacere
```suggestion
Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice originale, si creano differenti versioni, ognuna delle quali introduce una mutazione, piccola a piacere. Queste versioni mutate vengono chiamati _mutanti_. L'obiettivo del mutation testing è di verificare se la test suite identifica la mutazione: se un mutante non viene rilevato da un test, viene considerato _vivo_ e i test a riguardo vengono considerati non sufficienti per quella mutazione. Se un mutante viene rilevato da un test, viene considerato _morto_ e i test a riguardo vengono considerati sufficienti per quel mutante.
```

2024-02-24 09:52 UTC, Cadienvan commented
@BrianAtzori @guizzo ho rivisto il paragrafo modificando il "diversi diversi" ripetuto, fatemi sapere se così vi torna di più!

2024-02-24 16:32 UTC, sensorario submitted a review, later dismissed

2024-02-26 14:50 UTC, BrianAtzori submitted a review, later dismissed

2024-03-04 21:45 UTC, corradopetrelli submitted a review, later dismissed
Approvo, solo una piccolezza se vogliamo

2024-03-04 21:45 UTC, corradopetrelli commented on docs/it/testing.md
> +Applicando la formula `mutation score = (mutanti morti / mutanti totali) * 100`, possiamo ottenere una percentuale di mutanti morti, che ci permette di capire quanto il nostro codice sia realmente te
```suggestion
Applicando la formula $mutation\ score = \dfrac{mutanti\ morti}{mutanti\ totali} * 100$, possiamo ottenere una percentuale di mutanti morti, che ci permette di capire quanto il nostro codice sia realmente testato.
```

Uscirebbe fuori così ⏬ ⏬ ⏬ 
Applicando la formula $mutation\ score = \dfrac{mutanti\ morti}{mutanti\ totali} * 100$, possiamo ottenere una percentuale di mutanti morti, che ci permette di capire quanto il nostro codice sia realmente testato.

2024-03-13 11:50 UTC, BrianAtzori submitted a review, later dismissed
Ci siamo! Per me é ok (Ero convinto di aver giá fatto la review 🤷🏻‍♂️)

2024-03-15 10:35 UTC, sensorario approved these changes

2024-03-15 19:51 UTC, Cadienvan commented
Colpa di @corradopetrelli che ha chiesto modifiche ahahahah

2024-03-15 20:02 UTC, corradopetrelli commented
> Colpa di @corradopetrelli che ha chiesto modifiche ahahahah

Prego

2024-03-15 20:02 UTC, corradopetrelli submitted a review, later dismissed

2024-03-16 09:23 UTC, serenasensini commented on docs/it/testing.md
> +Pur essendo un'ottimo strumento per misurare la qualità della test suite, in molti casi questa tecnica di testing non è usata per via della sua complessità e costo di implementazione.
```suggestion
Pur essendo un ottimo strumento per misurare la qualità della test suite, in molti casi questa tecnica di testing non è usata per via della sua complessità e del costo di implementazione.
```

2024-03-16 09:23 UTC, serenasensini commented on docs/it/testing.md
>  La test coverage è una metrica che indica la percentuale di codice sorgente che viene eseguita (_coperta_) durante l'esecuzione dei test. Questa metrica è molto importante, in quanto permette di capi
```suggestion
La test coverage è una metrica che indica la percentuale di codice sorgente che viene eseguita (_coperta_) durante l'esecuzione dei test. Questa metrica è molto importante, in quanto permette di capire quanto il codice sorgente è stato testato. Solitamente si cerca di raggiungere una test coverage del 100%, ma questo non è sempre possibile, oltre che necessario. Infatti, una test coverage del 100% non garantisce che il codice sorgente sia privo di bug, esattamente come non lo garantisce una coverage del 50%. Come in moltissimi altri aspetti della programmazione, la parola _dipende_ assume un significato molto importante.
```

2024-03-16 15:33 UTC, lmammino approved these changes
Approvato con qualche piccolo consiglio :)

2024-03-16 15:33 UTC, lmammino commented on docs/it/testing.md
> +Il mutation testing è una metodologia di test per valutare l'attuale test suite. Partendo dal codice originale, si creano differenti versioni, ognuna delle quali introduce una mutazione, piccola a pi
Menzionerei l'aspetto qualità anche all'inizio per chiarire da subito qual é lo scopo di questo tipo di test.

```suggestion
Il mutation testing è una metodologia di test per valutare la qualità dell'attuale test suite. Partendo dal codice originale, si creano differenti versioni, ognuna delle quali introduce una mutazione, piccola a piacere. Queste versioni mutate vengono chiamati _mutanti_. L'obiettivo del mutation testing è di verificare se la test suite identifica la mutazione: se un mutante non viene rilevato da un test, viene considerato _vivo_ e i test a riguardo vengono considerati non sufficienti per quella mutazione. Se un mutante viene rilevato da un test, viene considerato _morto_ e i test a riguardo vengono considerati sufficienti per quel mutante.
```

2024-03-16 15:33 UTC, lmammino commented on docs/it/testing.md
> +
Non so se sarebbe il caso di menzionare che i mutation test spesso non vengono scritti a mano, ma vengono utilizzati dei tool ad hoc come:

- https://infection.github.io/guide/ (Php)
- https://stryker-mutator.io/ (JavaScript)
- https://mutants.rs/ (Rust)

2024-03-16 16:13 UTC, Cadienvan commented on docs/it/testing.md
> +
Mi torna, provo ad aggiungere un pezzo!

2024-03-16 16:15 UTC, Cadienvan commented on docs/it/testing.md
> +Pur essendo un ottimo strumento per misurare la qualità della test suite, in molti casi questa tecnica di testing non è usata per via della sua complessità e del costo di implementazione.
```suggestion
Pur essendo un ottimo strumento per misurare la qualità della test suite, in molti casi questa tecnica di testing non è usata per via della sua complessità e del costo di implementazione.

Esistono strumenti, anche open-source, che possono automatizzare la scrittura di questi test, come Infection (PHP), Stryker Mutator (JavaScript) o Mutants (Rust), riducendo radicalmente la complessità di adottare questa tecnica.
```

2024-03-16 16:15 UTC, Cadienvan commented on docs/it/testing.md
> +
@lmammino ti piace così?

2024-03-16 16:34 UTC, lmammino commented on docs/it/testing.md
> +
@Cadienvan ASSAI!

2024-03-16 17:59 UTC, lmammino approved these changes

2024-03-17 14:59 UTC, AngeloAvv approved these changes

2024-03-18 20:50 UTC, BrianAtzori approved these changes

2024-05-04 13:47 UTC, giuppidev approved these changes
Onestamente non conoscevo bene il mutation testing e dal capitolo mi è stato introdotto perfettamente. Complimenti!

2024-05-04 13:48 UTC, davideimola approved these changes

2024-05-04 17:31 UTC, serenasensini reviewed
Per me, super ok le correzioni già presenti!

2024-05-04 18:59 UTC, merged

2024-05-05 10:40 UTC, akelity approved these changes
Direi ottimo!