+capitolo AI
Il-Libro-Open-Source/book pull request #221
Opened 2024-03-13 21:56 UTC by serenasensini

Prima bozza del capitolo dedicato all'intelligenza artificiale. Enjoy! 🔥

2024-03-17 15:47 UTC, Cadienvan approved these changes
Io l'avevo già letto in anteprima - la fortuna dei raccomandati - e mi piace molto!

Come ti accennavo in privato non so se abbia senso citare RAG e 1-bit LLM, che ne pensi?

2024-03-17 18:36 UTC, AngeloAvv requested changes
Bella :bomb: 

Ho aggiunto un mio piccolo contributo e segnalati alcuni typo! Nice job :mechanical_arm:

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Per dare un'ulteriore livello di dettaglio, andiamo a definire quelle che sono le tecniche appartenenti a ciascuna delle categorie prima citate, in maniera più puntuale.
```suggestion
Per dare un ulteriore livello di dettaglio, andiamo a definire quelle che sono le tecniche appartenenti a ciascuna delle categorie prima citate, in maniera più puntuale.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +2.  Apprendimento non supervisionato: gli algoritmi trovano modelli nei dati senza etichette predefinite. In questo caso, è il modello a dover individuare dei pattern ricorrenti nei dati per individu
Typo
```suggestion
2.  Apprendimento non supervisionato: gli algoritmi trovano modelli nei dati senza etichette predefinite. In questo caso, è il modello a dover individuare dei pattern ricorrenti nei dati per individuare possibili correlazioni tra i dati. In questo caso, un esempio di applicazione è quello legato allo studio dei segmenti di clienti in ambito marketing; per analizzare il mercato di un dato settore, può essere utile non avere delle etichette a priori, ma piuttosto dare al modello il compito di segmentare i clienti in base a correlazioni che sarebbero difficili in forma manuale su grandi moli di dati.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +3.  Apprendimento semi-supervisionato: combina l'apprendimento supervisionato e non supervisionato utilizzando dati etichettati e non etichettati.
Ti ho trovato un esempio :laughing: 
Ci ho fatto la tesi :smiling_face_with_tear: 

```suggestion
3.  Apprendimento semi-supervisionato: combina l'apprendimento supervisionato e non supervisionato utilizzando dati etichettati e non etichettati ed è particolarmente adoperato nei problemi di classificazione. Un esempio di applicazione è legato all'etichettatura di aree geografiche analizzando scatti fotografici provenienti dai satelliti. Le lievi variazioni sullo spettro dell'immagine consentono all'operatore di etichettare un piccolo subset di dati che verrà poi esteso automaticamente dall'algoritmo.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +4.  Apprendimento per rinforzo: gli agenti imparano a prendere decisioni interagendo con un ambiente. Un po' come avviene come nei sistemi di risposta automatica, il feedback dell'utente permette al
Ripetizione

```suggestion
4.  Apprendimento per rinforzo: gli agenti imparano a prendere decisioni interagendo con un ambiente. Un po' come avviene nei sistemi di risposta automatica, il feedback dell'utente permette al sistema di valutare il proprio operato durante lo svolgimento dello stesso.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Tra le applicazioni principali nel campo del Deep learning ci sono:
```suggestion
Tra le applicazioni principali nel campo del deep learning ci sono:
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +3.  Rilevamento delle frodi, in campo assicurativo e bancario, utilizzato per rilevare attività fraudolente;
Per evitare le ripetizione
```suggestion
3.  Rilevamento delle frodi, in campo assicurativo e bancario, utilizzato per rilevare attività criminali;
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +5.  Personalizzazione: Utilizzato per creare esperienze su misura come consigli sui prodotti e servizi personalizzati.
Ho visto che avevi iniziato con i ;

```suggestion
4.  Assistenza sanitaria: le applicazioni includono il supporto alla diagnosi di malattie, la prognosi e le tecniche di imaging medico;
5.  Personalizzazione: utilizzato per creare esperienze su misura come consigli sui prodotti e servizi personalizzati;
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Nel campo del Deep learning, tra gli algoritmi più utilizzati ci sono:
```suggestion
Nel campo del deep learning, tra gli algoritmi più utilizzati ci sono:
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +- Reti neurali convoluzionali (CNN):, utilizzate principalmente per attività di riconoscimento delle immagini;
Qui è scappata via una virgola :laughing: 
```suggestion
- Reti neurali convoluzionali (CNN): utilizzate principalmente per attività di riconoscimento delle immagini;
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +- Backpropagation: fondamentale per addestrare le reti neurali in modo efficiente.
Dici che è il caso di riportare l'equivalente in inglese dell'acronimo?
```suggestion
- Memoria a lungo termine (LSTM): essenziale per le reti neurali ricorrenti e l'elaborazione sequenziale dei dati;
- Backpropagation: fondamentale per addestrare le reti neurali in modo efficiente;
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +- Claude: il LLM di prossima generazione di Anthropic utilizzato nei chatbot conversazionali.
Qui vedo che l'hai riportata la definizione. Anche qui forse vanno i ;

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Altra branca estremamente importante è quella relativa alla data science, che combina strumenti, metodi e tecnologie statistici per generare significato dai dati, tramite il concetto di inferenza. An
Typo

```suggestion
Altra branca estremamente importante è quella relativa alla data science, che combina strumenti, metodi e tecnologie statistici per generare significato dai dati, tramite il concetto di inferenza. Anche questa è spesso confusa con il concetto di intelligenza artificiale, della quale ne è -appunto- una categoria: infatti, la data science trova applicazione nell'ambito predittivo, necessita di dati di ottima qualità e può sfruttare tecniche di ML per raggiungere una serie di obiettivi, come riconoscere dei modelli nei dati a disposizione.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Garantire un’intelligenza artificiale etica è essenziale per prevenire pregiudizi, salvaguardare la privacy, evitare errori che potrebbero causare danni e gestire l’impatto ambientale delle tecnologi
```suggestion
Garantire un’intelligenza artificiale etica è essenziale per prevenire pregiudizi, salvaguardare la privacy, evitare errori che potrebbero causare danni e gestire l’impatto ambientale delle tecnologie di intelligenza artificiale. Basti pensare a sistemi di questo tipo applicati nell'ambito della sanità: quali sono i limiti con cui progettare un sistema che sfrutti l'intelligenza artificiale per interagire con possibili pazienti? In che modo vengono trattati i dati inseriti da questi, e come valutare l'operato? Seguendo i principi etici nello sviluppo e nell’utilizzo dell’intelligenza artificiale, le aziende possono mitigare rischi come guasti dei prodotti, problemi legali e danni al marchio. L’intelligenza artificiale etica non riguarda solo il comportamento responsabile, ma anche la garanzia di un buon valore aziendale e del benessere sociale.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +Tuttavia, la laurea non è un requisito mandatorio, ma piuttosto un qualcosa che può supportare nella definizione di una forma mentis e di un percorso lineare per approcciarsi al tema.
Piace tantissimo anche a me questo termine però forse è meglio semplificare :laughing: 
```suggestion
Tuttavia, la laurea non è un requisito obbligatorio, ma piuttosto un qualcosa che può supportare nella definizione di una forma mentis e di un percorso lineare per approcciarsi al tema.
```

2024-03-17 18:36 UTC, AngeloAvv commented on docs/it/ai.md
> +La domanda di professionisti/e dell’IA è elevata, con opportunità di crescita e innovazione in tutti i settori. Competenze specializzate in linguaggi di programmazione come Python e Java, modellazion
R è sempre bistrattato :laughing: 
```suggestion
La domanda di professionisti/e dell’IA è elevata, con opportunità di crescita e innovazione in tutti i settori. Competenze specializzate in linguaggi di programmazione come Python, R e Java, modellazione dei dati, machine learning, deep learning e familiarità con framework come TensorFlow e PyTorch sono cruciali per il successo nelle carriere nel campo dell'intelligenza artificiale.
```

2024-03-18 20:56 UTC, BrianAtzori commented
Questo non vedo l'ora di leggerlo! Nei prossimi giorni faccio anche io una review, magari già domani 🔝

2024-03-19 10:17 UTC, BrianAtzori approved these changes
Approvo salvo il piccolo typo che ho trovato perchè tutto quello che ho trovato l'aveva già corretto il buon @AngeloAvv, per me é un ottimo capitolo soprattuto perché spesso le risorse che si trovano online guardano sempre il lato positivo ma mai quelli negativi e non viene mai menzionata l'etica dell'argomento

Uno spunto, magari anche per un'espansione futura potrebbe essere annettere il tema ambientale alla parte sull'etica, quindi consumi energetici ecc ecc

Complimenti intanto @serenasensini !

2024-03-24 14:54 UTC, nicolaerario commented on docs/it/ai.md
> +Per questa ragione, ad oggi, esiste un forte divario su ciò che sia un'intelligenza artificiale: più genericamente parlando, possiamo pensare a sistemi intelligenti come sistemi che possano emulare u
all essere umano -> all'essere umano

2024-03-26 22:44 UTC, serenasensini commented on docs/it/ai.md
> +Per dare un'ulteriore livello di dettaglio, andiamo a definire quelle che sono le tecniche appartenenti a ciascuna delle categorie prima citate, in maniera più puntuale.
Come mi è sfuggita una cosa del genere... 🥲

2024-03-26 22:47 UTC, serenasensini commented
> Approvo salvo il piccolo typo che ho trovato perchè tutto quello che ho trovato l'aveva già corretto il buon @AngeloAvv, per me é un ottimo capitolo soprattuto perché spesso le risorse che si trovano online guardano sempre il lato positivo ma mai quelli negativi e non viene mai menzionata l'etica dell'argomento
> 
> Uno spunto, magari anche per un'espansione futura potrebbe essere annettere il tema ambientale alla parte sull'etica, quindi consumi energetici ecc ecc
> 
> Complimenti intanto @serenasensini !

Sicuramente sul blog TheRedCode.it uscirà un articolo a tema Green AI nelle prossime settimane, quindi posso pensare di includere anche qui qualche riferimento... Grazie del feedback e del suggerimento!

2024-03-26 22:47 UTC, serenasensini commented
> Io l'avevo già letto in anteprima - la fortuna dei raccomandati - e mi piace molto!
> 
> Come ti accennavo in privato non so se abbia senso citare RAG e 1-bit LLM, che ne pensi?

Ci sta. Li metto in coda!

2024-03-26 22:48 UTC, serenasensini commented
> Bella 💣
> 
> Ho aggiunto un mio piccolo contributo e segnalati alcuni typo! Nice job 🦾

Grazie mille! Alcune cose mi sono sfuggite e non mi spiego neanche come sia possibile 🥲 integro le correzioni e aggiungo qualche sezione in più nelle prossime settimane!

2024-04-11 19:48 UTC, BrianAtzori approved these changes

2024-04-13 13:36 UTC, Cadienvan submitted a review, later dismissed

2024-04-15 13:25 UTC, AngeloAvv approved these changes

2024-04-27 07:32 UTC, Cadienvan submitted a review, later dismissed

2024-04-27 14:16 UTC, AngeloAvv submitted a review, later dismissed

2024-05-04 10:55 UTC, BrianAtzori submitted a review, later dismissed

2024-05-04 14:21 UTC, passasooz submitted a review, later dismissed

2024-05-05 08:58 UTC, nicolaerario requested changes

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +Per questa ragione, ad oggi, esiste un forte divario su cosa sia un'intelligenza artificiale: più genericamente parlando, possiamo pensare ai sistemi intelligenti come sistemi che possano emulare una
```suggestion
Per questa ragione, ad oggi, esiste un forte divario su cosa sia un'intelligenza artificiale: più genericamente parlando, possiamo pensare ai sistemi intelligenti come sistemi che possano emulare una data capacità associata normalmente all essere umano in grado di ottenere risultati altrettanto verosimili. Inutile dire che a sostegno di questa definizione spesso si accostano i celebri Test di Turing: il matematico britannico tentò di formulare delle prove che potessero "misurare" e verificare la differenza tra un sistema di intelligenza artificiale e un essere umano nello svolgere un dato compito. Ad oggi, molte delle domande che Turing si è posto per affermare o meno se un sistema fosse intelligente hanno perso di valenza e risultano superate, ma, al tempo, erano certamente di valido ausilio.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +Il termine che definisce questo settore nasce quasi un secolo fa: John McCarthy, uno dei personaggi più illustri del settore, battezza quei sistemi dotati di capacità assimilabili a competenze umane
`partendo dall'assunto che la stessa definizione di "intelligenza" può assumere diverse ` => qui non mi suona molto assunto + assumere (considerando che,più avanti, ritorna un "assume"

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +    Un altro campo è quello chiamato Self-Aware AI (concettuale): immagina sistemi di intelligenza artificiale in grado di costruire opinioni ed emozioni su se stessi indipendentemente dai dati immes
```suggestion
    Un altro campo è quello chiamato Self-Aware AI (concettuale): immagina sistemi di intelligenza artificiale in grado di costruire opinioni ed emozioni su se stessi indipendentemente dai dati immessi dall'uomo, trasformando la tecnologia e la vita umana. Questo presuppone la presenza di una coscienza, di senso etico e di esperienza; tutte caratteristiche ad oggi ancora non formalizzate.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +2.  Apprendimento non supervisionato: gli algoritmi trovano modelli nei dati senza etichette predefinite. In questo caso, è il modello a dover individuare dei pattern ricorrenti nei dati per individu
evito il doppio `in questo caso`
```suggestion
2.  Apprendimento non supervisionato: gli algoritmi trovano modelli nei dati senza etichette predefinite. In questo caso, è il modello a dover individuare dei pattern ricorrenti nei dati per individuare possibili correlazioni tra i dati. Un esempio di applicazione è quello legato allo studio dei segmenti di clienti in ambito marketing; per analizzare il mercato di un dato settore, può essere utile non avere delle etichette a priori, ma piuttosto dare al modello il compito di segmentare i clienti in base a correlazioni che sarebbero difficili in forma manuale su grandi moli di dati.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +1.  Apprendimento supervisionato: gli algoritmi apprendono dai dati etichettati per fare previsioni. Per etichetta, si intende una categoria o una classe che serve a identificare il dato rappresentat
c'è uso promisquo di `etichette` e `label`; forse questo risolve?
```suggestion
1.  Apprendimento supervisionato: gli algoritmi apprendono dai dati etichettati per fare previsioni. Per etichetta, si intende una categoria o una classe che serve a identificare il dato rappresentato. Un esempio è quello che prevede la classificazione di immagini di cuccioli di cane e di coniglio che vengono distinte tramite delle etichette (label) per descriverne la specie, così che il modello possa sfruttare queste label per associare ogni nuova immagine alla label corretta, una volta completato l'addestramento.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +La back propagation consiste nell'utilizzare dei pesi per misurare le risposte ottenute dai singoli neuroni e propagare l'errore ottenuto nelle predizioni nei neuroni precedenti, così da poter aument
```suggestion
La backpropagation consiste nell'utilizzare dei pesi per misurare le risposte ottenute dai singoli neuroni e propagare l'errore ottenuto nelle predizioni nei neuroni precedenti, così da poter aumentare il livello di efficacia dell'algoritmo.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +Questo avviene grazie ai cosiddetti modelli linguistici: questi sono un’ampia categoria di sistemi di intelligenza artificiale che funzionano con il linguaggio, mentre i modelli linguistici di grandi
> Questo avviene grazie ai cosiddetti modelli linguistici: questi sono un’ampia categoria di sistemi di intelligenza artificiale che funzionano con il linguaggio, mentre i modelli linguistici di grandi dimensioni (abbreviati in LLM) si riferiscono specificamente a sistemi focalizzati sul linguaggio addestrati su enormi set di dati.

Non mi funziona particolarmente `mentre`: prende un'accezione avversativa non voluta (credo)

```suggestion
Questo avviene grazie ai cosiddetti modelli linguistici, un’ampia categoria di sistemi di intelligenza artificiale che funzionano con il linguaggio. I modelli linguistici di grandi dimensioni (abbreviati in LLM), nello specifico, si riferiscono poi a sistemi focalizzati sul linguaggio addestrati su enormi set di dati. Gli LLM utilizzano dei trasformatori, ossia risorse che permettono di sfruttare il concetto di euristica dei dati, e dispongono di un gran numero di parametri, che consentono loro di riconoscere, tradurre, prevedere o generare testo. Vengono utilizzati in varie applicazioni come traduzione, chatbot e assistenti IA. Spesso l'elaborazione del linguaggio naturale è associata a quella che si chiama intelligenza artificiale generativa: questa è una branca con ampia applicabilità, dal momento che uno degli scopi è quello di ottenere dei dati sintetici (quindi, generati e simili a quelli reali) da utilizzare per altre tipologie di operazioni. Un esempio è quello relativo alla generazione di immagini utilizzabili ai fini di ricerca nel campo medico, senza la necessità di trovare dati che sarebbero invece difficilmente reperibili.
```

2024-05-05 08:58 UTC, nicolaerario commented on docs/it/ai.md
> +# Etica e intelligenza artificiale: uno scontro titanico
```suggestion
## Etica e intelligenza artificiale: uno scontro titanico
```

2024-05-31 09:19 UTC, serenasensini commented on docs/it/ai.md
> +Il termine che definisce questo settore nasce quasi un secolo fa: John McCarthy, uno dei personaggi più illustri del settore, battezza quei sistemi dotati di capacità assimilabili a competenze umane
```suggestion
Il termine che definisce questo settore nasce quasi un secolo fa: John McCarthy, uno dei personaggi più illustri del settore, battezza quei sistemi dotati di capacità assimilabili a competenze umane come "intelligenti". Nel corso degli anni questa definizione muta e si evolve, soprattutto se pensiamo che la stessa definizione di "intelligenza" può assumere diverse rappresentazioni: si parla di intelligenza logica, o emotiva? Di intelligenza matematica o motoria? Ognuna di queste richiede capacità diverse e assume forme differenti, spesso difficili da riprodurre tramite semplici regole o equazioni.
```

2024-05-31 09:55 UTC, sensorario submitted a review, later dismissed

2024-06-01 16:36 UTC, Cadienvan commented on docs/it/ai.md
> +# AI
```suggestion
---
layout: default
title: AI
nav_order: 13
---

<!-- prettier-ignore-start -->
# AI
{: .no_toc }

- TOC
{:toc}

<!-- prettier-ignore-end -->
```

2024-06-01 16:37 UTC, merged