Aggiunto file principale per documentazione
Il-Libro-Open-Source/book pull request #223
Opened 2024-03-19 12:55 UTC by federico-trotta

Aggiunto il file principale della documentazione che spiega la necessità e l'importanza della documentazione ed anticipa le tematiche di cui trattare successivamente nelle sotto sezioni (verranno aggiunte successivamente).

2024-03-19 12:56 UTC, federico-trotta commented
Risolti conflitti

2024-03-23 14:22 UTC, Cadienvan approved these changes

2024-03-23 14:24 UTC, Cadienvan commented
CIao @federico-trotta, a me piace molto, infatti di base ho approvato il contenuto. Credo però che manchi un punto iniziale nella discussione e un'aggiunta nel mezzo. Provo a spiegarmi.

Si parte subito col dire che la documentazione è un'attività secondaria, senza però indicare cosa sia. Partendo dal presupposto che chi legge questo contenuto dovrebbe saperlo, potrebbe non essere così, quindi spiegherei cos'è una documentazione tecnica e, magari, alcuni accorgimenti su come scriverla (Evitare i papiri, arrivare dritti al punto, spiegare bene il contesto attorno a quanto si sta leggendo, ecc.). Cosa ne pensi?

Inoltre, credo che nel mezzo starebbe molto bene un accenno ai tool, come markdown, che possono favorire la stesura di documentazione. Non andrei in quelli enterprise come Confluence in quanto, appunto, business-related, ma più su tool di facile accesso.

2024-03-23 19:14 UTC, federico-trotta commented
Ciao @Cadienvan hai sollevato ottimi punti!

Concordo di non trattare tool specifici. Parlerei del markdown in via principale; in via secondaria, accennerei al reSTructured text perché è mooooolto utile per documentare progetti Python (è utile in generale come il markdown, ma resterei a Python in quanto discussione più adatta per un pubblico di developers).

Penso di lavorarci in settimana. :)

2024-03-25 11:09 UTC, Cadienvan commented
Mi torna!

2024-03-27 19:49 UTC, corradopetrelli approved these changes

2024-03-30 13:02 UTC, Cadienvan commented on docs/it/documentazione.md
> +Esistono diveri tools commerciali e linguaggi per sviluppare la documentazione tecnica. In questa sezione, non tratteremo i diversi tools commerciali in quanto il loro utilizzo è legato a scelte pref
```suggestion
Esistono diveri tool commerciali e linguaggi per stendere documentazione tecnica. In questa sezione, non tratteremo i diversi tool commerciali in quanto il loro utilizzo è legato a scelte aziendali. Ad ogni modo, si tratta spesso di strumenti che non richiedono particolari conoscenze e competenze, per cui sono facili da imparare per un pubblico che abbia delle conoscenze informatiche di base.
```

2024-03-30 13:02 UTC, Cadienvan commented on docs/it/documentazione.md
> +E' importante, invece, conoscere i linguaggi utilizzati per svilupare la documentazione tecnica. Nello specifico, il Markdown ed il reStructuredText (reST) sono due linguaggi di markup ampiamente uti
```suggestion
È importante, invece, conoscere i _linguaggi_ utilizzati per stendere tale documentazione. Nello specifico, il Markdown ed il reStructuredText (reST) sono due linguaggi di markup ampiamente utilizzati per la formattazione di documenti testuali, ma con scopi e funzionalità leggermente diversi.
```

2024-03-30 13:03 UTC, Cadienvan commented on docs/it/documentazione.md
> +Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web
```suggestion
Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web e altro ancora. La sua sintassi è intuitiva e semplice, ed è supportato da molti editor di testo e piattaforme di hosting come GitHub, che lo rende una scelta popolare tra gli sviluppatori e i professionisti del settore tecnologico. È sicuramente la scelta preferenziale quando si voglia iniziare a documentare un progetto legato al software.
```

2024-03-30 13:04 UTC, Cadienvan commented on docs/it/documentazione.md
> +Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progett
```suggestion
Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progettato per creare documentazione tecnica e di progetto in modo chiaro e coerente.  È utilizzato principalmente per scrivere documentazione di progetti Python, grazie al suo stretto legame con il tool di generazione della documentazione [Sphinx](https://www.sphinx-doc.org/en/master/), il quale consente di compilare la documentazione scritta in reST in vari formati, inclusi HTML, PDF e ePub, facilitando la distribuzione e la consultazione della documentazione di progetto. Il reST richiede una curva di apprendimento leggermente più ripida rispetto al Markdown, ma offre una maggiore flessibilità e potenza per la creazione di documentazione più strutturata e complessa. È naturalmente anch'esso integrabile con i più noti IDE, ed è supportato dalle più note piattaforme di hosting, come GitHub.
```

2024-03-30 13:04 UTC, Cadienvan reviewed
Messe un paio di correzioni, mi piace molto!!

2024-04-01 11:32 UTC, Cadienvan approved these changes

2024-04-04 20:59 UTC, ugho16 approved these changes
Piccole proposte e suggerimenti per rendere il linguaggio più neutro.
In quanto tech writer sono molto sensibile al tema docs e mi è piaciuto molto questo capitolo!

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +Considerando il punto di vista degli sviluppatori, in generale, la documentazione tecnica serve per descrivere i seguenti aspetti del software:
```suggestion
Considerando il punto di vista di chi sviluppa, in generale, la documentazione tecnica serve per descrivere i seguenti aspetti del software:
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +- **Le specifiche di progettazione**. Questa parte della documentazione comprende informazioni sulle funzionalità del software, i requisiti di sistema, le prestazioni attese e le limitazioni conosciu
```suggestion
- **Le specifiche di progettazione**. Questa parte della documentazione comprende informazioni sulle funzionalità del software, i requisiti di sistema, le prestazioni attese e le limitazioni conosciute. Questo aiuta i team di sviluppo a comprendere appieno il comportamento atteso dal software e a progettare soluzioni appropriate per le esigenze specifiche.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +- **Guide per gli sviluppatori**. Questa parte della documentazione fornisce istruzioni dettagliate su come configurare l'ambiente di sviluppo, come compilare il codice sorgente, come eseguire i test
```suggestion
- **Guide per chi sviluppa**. Questa parte della documentazione fornisce istruzioni dettagliate su come configurare l'ambiente di sviluppo, come compilare il codice sorgente, come eseguire i test, e come contribuire al progetto in base agli standard prefissati. Questa guida è essenziale per consentire a nuovi membri di integrarsi rapidamente nel team e contribuire in modo efficace al software.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +La documentazione non è semplicemente un compito aggiuntivo per i dev, incastrati come sono tra riunioni (tante) e sviluppo (spesso, poco). Piuttosto, è un elemento cruciale per garantire la comprens
```suggestion
La documentazione non è semplicemente un compito aggiuntivo per chi programma, da incastrare tra le riunioni (tante) e lo sviluppo (spesso, poco). Piuttosto, è un elemento cruciale per garantire la comprensione, la manutenibilità, e l'evoluzione del software stesso. 
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +In primo luogo, la documentazione svolge un ruolo fondamentale nella comprensione del software. Il codice può essere complesso e intricato - e tutt'altro che "self-documenting"! . La documentazione,
```suggestion
In primo luogo, la documentazione svolge un ruolo fondamentale nella comprensione del software. Il codice può essere complesso e intricato - e tutt'altro che "self-documenting"! . La documentazione, invece, fornisce un'annotazione chiara e comprensibile di ciò che fa il software, di come è strutturato e come interagisce con altri componenti del sistema. Questo è particolarmente cruciale per consentire ai nuovi membri del team di integrarsi rapidamente in un progetto avviato, ed ai membri esistenti di lavorare in modo efficiente ed efficace.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +In secondo luogo, la documentazione facilita la manutenzione del software nel tempo. Con una documentazione accurata, infatti, i problemi possono essere individuati e risolti più rapidamente, poiché
```suggestion
In secondo luogo, la documentazione facilita la manutenzione del software nel tempo. Con una documentazione accurata, infatti, i problemi possono essere individuati e risolti più rapidamente, poiché si ha a disposizione una guida chiara su come il software sia stato progettato e implementato. Senza una documentazione adeguata, la manutenzione del software diventa un compito arduo e laborioso, aumentando il rischio di errori e ritardi nel rilascio delle correzioni.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +Infine, la documentazione è essenziale per garantire la continuità del business. Nel caso in cui i membri del team lascino l'organizzazione o cambino ruolo, una documentazione completa e aggiornata c
```suggestion
Infine, la documentazione è essenziale per garantire la continuità del business. Nel caso in cui i membri del team lascino l'organizzazione o cambino ruolo, una documentazione completa e aggiornata consente una transizione fluida e minimizza l'impatto sul progetto. Senza una documentazione adeguata, l'organizzazione rischia di perdere conoscenze critiche e di subire interruzioni nei progetti software in corso. Allo stesso modo, la documentazione è fondamentale qualora un progetto venga dato in outsourcing ad una azienda terza. Fare reverse engineering del codice è spesso una necessità, ma avere documentato il progetto permette all'azienda terzista ed ai suoi team di sviluppo di risparmiare tempo, e di avere delle linee guida chiare da seguire, potendo capire il ciclo di vita del prodotto per come è stato pensato fino a quel momento.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +- **Conoscere il pubblico**. Prima di iniziare a scrivere, è fondamentale comprendere chi sarà il pubblico che leggerà ed utilizzerà la documentazione. Per esempio: ci stiamo rivolgendo ad un pubblic
```suggestion
- **Conoscere il pubblico**. Prima di iniziare a scrivere, è fondamentale comprendere chi sarà il pubblico che leggerà ed utilizzerà la documentazione. Per esempio: ci stiamo rivolgendo ad un pubblico composto esclusivamente da figure senior o è necessario considerare anche un pubblico di junior? Ci rivolgiamo ad una platea nazionale o internazionale? Gli utenti finali avranno sicuramente esigenze diverse in base alla loro seniority, ma anche alla lingua usata per scrivere la documentazione. Per cui, adattare lo stile, il livello di dettaglio, ed il linguaggio utilizzato in base al pubblico aiuterà a garantire che la documentazione sia utile ed efficace ad uno specifico pubblico.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +- **Essere chiari e concisi**. È importante evitare l'uso di gergo tecnico e complesso quando non necessario, per far sì che il proprio pubblico comprenda chiaramente la documentazione. Allo stesso m
```suggestion
- **Esprimersi con chiarezza e concisione**. È importante evitare l'uso di gergo tecnico e complesso quando non necessario, per far sì che il proprio pubblico comprenda chiaramente la documentazione. Allo stesso modo, è importante mantenere le descrizioni concise, evitando ripetizioni e informazioni superflue: la chiarezza è fondamentale e spiegare i concetti in modo semplice e diretto, evitando ambiguità e confusione, è l'obiettivo da tenere sempre a mente.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +## Linguaggi per sviluppare al documentazione tecnica
```suggestion
## Linguaggi per sviluppare la documentazione tecnica
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +Esistono diveri tool commerciali e linguaggi per stendere documentazione tecnica. In questa sezione, non tratteremo i diversi tool commerciali in quanto il loro utilizzo è legato a scelte aziendali.
```suggestion
Esistono diversi tool commerciali e linguaggi per stendere documentazione tecnica. In questa sezione, non tratteremo i diversi tool commerciali in quanto il loro utilizzo è legato a scelte aziendali. Ad ogni modo, si tratta spesso di strumenti che non richiedono particolari conoscenze e competenze, per cui sono facili da imparare per un pubblico che abbia delle conoscenze informatiche di base.
```

2024-04-04 20:59 UTC, ugho16 commented on docs/it/documentazione.md
> +Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web
```suggestion
Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web e altro ancora. La sua sintassi è intuitiva e semplice, ed è supportato da molti editor di testo e piattaforme di hosting come GitHub, che lo rende una scelta popolare tra developer e figure professionali del settore tecnologico. È sicuramente la scelta preferenziale quando si voglia iniziare a documentare un progetto legato al software.
```

2024-04-05 19:41 UTC, Cadienvan approved these changes

2024-04-09 07:39 UTC, elgorditosalsero requested changes

2024-04-09 08:29 UTC, guizzo reviewed
@federico-trotta Ho piazzato qualche suggestions qua e là; sentiti libero di accettarle o rifiutarle :)

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +La documentazione del software è spesso vista come un'attività secondaria, e viene spesso trascurata in favore dello sviluppo del codice. Tuttavia, sottovalutarne l'importanza può avere conseguenze s
```suggestion
La documentazione del software è spesso vista come un'attività secondaria, e viene spesso trascurata in favore dello sviluppo del codice. Tuttavia, sottovalutarne l'importanza può avere conseguenze significative sul ciclo di vita del software e sulla sua gestione dello stesso a lungo termine.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +La documentazione non è semplicemente un compito aggiuntivo per chi programma, da incastrare tra le riunioni (tante) e lo sviluppo (spesso, poco). Piuttosto, è un elemento cruciale per garantire la c
```suggestion
La documentazione non è semplicemente un compito aggiuntivo per chi programma, da incastrare tra le riunioni (tante) e lo sviluppo (spesso, poco). Piuttosto, è un elemento cruciale per garantire la comprensione, la manutenibilità e l'evoluzione del software stesso. 
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +Non meno importante, la documentazione del software è cruciale per la conformità normativa e la sicurezza. In settori come la sanità, la finanza, e la sicurezza informatica, è fondamentale tenere tra
```suggestion
Non meno importante, la documentazione del software è cruciale per la conformità normativa e la sicurezza. In settori come la sanità, la finanza e la sicurezza informatica, è fondamentale tenere traccia di come il software sia stato sviluppato, testato e implementato. In questi casi, inoltre, la documentazione fornisce una traccia chiara delle decisioni prese durante il processo di sviluppo e aiuta a dimostrare la conformità alle normative e agli standard di settore in caso di controlli.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +Infine, la documentazione è essenziale per garantire la continuità del business. Nel caso in cui i membri del team lascino l'organizzazione o cambino ruolo, una documentazione completa e aggiornata c
```suggestion
Infine, la documentazione è essenziale per garantire la continuità del business. Nel caso in cui i membri del team lascino l'organizzazione o cambino ruolo, una documentazione completa e aggiornata consente una transizione fluida e minimizza l'impatto sul progetto. Senza una documentazione adeguata, l'organizzazione rischia di perdere conoscenze critiche e di subire interruzioni nei progetti software in corso. Allo stesso modo, la documentazione è fondamentale qualora un progetto venga dato in outsourcing ad una azienda terza. Fare reverse engineering del codice è spesso una necessità, ma avere documentato il progetto permette all'azienda terzista ed ai suoi team di sviluppo di risparmiare tempo e di avere delle linee guida chiare da seguire, potendo capire il ciclo di vita del prodotto per come è stato pensato fino a quel momento.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +- **Conoscere il pubblico**. Prima di iniziare a scrivere, è fondamentale comprendere chi sarà il pubblico che leggerà ed utilizzerà la documentazione. Per esempio: ci stiamo rivolgendo ad un pubblic
```suggestion
- **Conoscere il pubblico**. Prima di iniziare a scrivere, è fondamentale comprendere chi sarà il pubblico che leggerà ed utilizzerà la documentazione. Per esempio: ci stiamo rivolgendo ad un pubblico composto esclusivamente da figure senior o è necessario considerare anche un pubblico di junior? Ci rivolgiamo ad una platea nazionale o internazionale? Gli utenti finali avranno sicuramente esigenze diverse in base alla loro seniority, ma anche alla lingua usata per scrivere la documentazione. Per cui, adattare lo stile, il livello di dettaglio ed il linguaggio utilizzato in base al pubblico aiuterà a garantire che la documentazione sia utile ed efficace ad uno specifico pubblico.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +- **Fornire esempi pratici**. Niente aiuta a comprendere un concetto più degli esempi pratici, specialmente in un ambiente legato allo sviluppo. Includere esempi di codice, casi d'uso, e scenari comu
```suggestion
- **Fornire esempi pratici**. Niente aiuta a comprendere un concetto più degli esempi pratici, specialmente in un ambiente legato allo sviluppo. Includere esempi di codice, casi d'uso e scenari comuni per illustrare i concetti in modo chiaro e tangibile è fondamentale.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web
```suggestion
Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web e altro ancora. La sua sintassi è intuitiva e semplice, ed è supportato da molti editor di testo e piattaforme di hosting come GitHub, che lo rende una scelta popolare tra developer e figure professionali del settore tecnologico. È sicuramente la scelta preferenziale quando si ha necessità di iniziare a documentare un progetto legato al software.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progett
```suggestion
Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progettato per creare documentazione tecnica e di progetto in modo chiaro e coerente. È utilizzato principalmente per scrivere documentazione di progetti Python, grazie al suo stretto legame con il tool di generazione della documentazione [Sphinx](https://www.sphinx-doc.org/en/master/), il quale consente di compilare la documentazione scritta in reST in vari formati, inclusi HTML, PDF e ePub, facilitando la distribuzione e la consultazione della documentazione di progetto. Il reST richiede una curva di apprendimento leggermente più ripida rispetto al Markdown, ma offre una maggiore flessibilità e potenza per la creazione di documentazione più strutturata e complessa. È naturalmente anch'esso integrabile con i più noti IDE, ed è supportato dalle più note piattaforme di hosting, come GitHub.
```

2024-04-09 08:29 UTC, guizzo commented on docs/it/documentazione.md
> +Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progett
```suggestion
Vale la pena menzionare anche il reStructuredText (reST) che è un linguaggio di markup più strutturato e flessibile, particolarmente popolare nell'ecosistema Python. Questo linguaggio è stato progettato per creare documentazione tecnica e di progetto in modo chiaro e coerente.  È utilizzato principalmente per scrivere documentazione di progetti Python, grazie al suo stretto legame con il tool di generazione della documentazione [Sphinx](https://www.sphinx-doc.org/en/master/), il quale consente di compilare la documentazione scritta in reST in vari formati, inclusi HTML, PDF e ePub, facilitando la distribuzione e la consultazione della documentazione di progetto. Il reST ha una curva di apprendimento leggermente più ripida rispetto al Markdown, ma offre una maggiore flessibilità e potenza per la creazione di documentazione più strutturata e complessa. È naturalmente anch'esso integrabile con i più noti IDE ed è supportato dalle più note piattaforme di hosting, come GitHub.
```

2024-04-13 13:35 UTC, Cadienvan commented
Ciao @federico-trotta ,
ho visto che mentre alcune suggestion le hai portate dentro, altre sono ancora pendenti. Non le reputi corrette oppure è stata solo una dimenticanza? Giusto per sapere, così riapprovo una volta sola ahah

2024-04-13 14:14 UTC, federico-trotta commented
Ciao @Cadienvan ,
i suggerimenti non committati li ritengo non corretti. :)

PS: il contenuto, comunque, ancora non è concluso, eh. Mancano ancora i seguenti:
- La gestione delle specifiche tecniche.
- La gestione delle specifiche di testing.
- La standardizzazione.
- La collaborazione coi Technical Writers (che però è un desiderata).

Lato mio, penso sia più giusto che qualche dev si occupi della parte della gestione delle specifiche tecniche e di testing (magari anche il buon @elgorditosalsero :) ), ed io do qualche indirizzo/suggerimento. 

Io lavorerò (spero in settimana!) sugli ultimi due, quindi standardizzazione e collaborazione coi tech writers (a cui seguiranno sicuramente suggerimenti da chi vorrà contribuire :) ).

Concordi? :)

2024-04-13 18:26 UTC, Cadienvan commented
Ci sto, mi piace!

2024-05-04 13:22 UTC, Cadienvan commented
@federico-trotta @elgorditosalsero piccolo amorevole ping che sapete sono "obbligato" a fare.. Come va con la stesura? Posso supportarvi in qualche modo?

2024-05-11 09:56 UTC, Cadienvan commented
Ottimo @federico-trotta , il ritardo che noti in questo commento ti fa capire che ti capisco molto bene ahahah nessuna fretta, io pingo a promemoria.

2024-06-12 07:11 UTC, guizzo approved these changes
LGTM

2024-06-26 19:44 UTC, BrianAtzori requested changes
Super capitolo, ho lasciato solo una correzione e un suggerimento, per il resto... top!

2024-06-26 19:44 UTC, BrianAtzori commented on docs/it/documentazione.md
> +- **Esprimersi con chiarezza e concisione**. È importante evitare l'uso di gergo tecnico e complesso quando non necessario (oppure spiegarlo chiaramente tramite un glossaio), per far sì che il propri
```suggestion
- **Esprimersi con chiarezza e concisione**. È importante evitare l'uso di gergo tecnico e complesso quando non necessario (oppure spiegarlo chiaramente tramite un glossario), per far sì che il proprio pubblico comprenda chiaramente la documentazione. Allo stesso modo, è importante mantenere le descrizioni concise, evitando ripetizioni e informazioni superflue: la chiarezza è fondamentale e spiegare i concetti in modo semplice e diretto, evitando ambiguità e confusione, è l'obiettivo da tenere sempre a mente.
```

2024-06-26 19:44 UTC, BrianAtzori commented on docs/it/documentazione.md
> +Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche in forma non formattata. È ampiamente utilizzato per scrivere documentazione, note, pagine web
```suggestion
Il Markdown è un linguaggio di markup leggero, progettato per essere facile da leggere e scrivere, anche quando non è formattato. È ampiamente utilizzato per scrivere documentazione, note, pagine web e altro ancora. La sua sintassi è intuitiva e semplice, ed è supportato da molti editor di testo e piattaforme di hosting come GitHub, che lo rende una scelta popolare tra developer e figure professionali del settore tecnologico. È sicuramente la scelta preferenziale quando si ha necessità di iniziare a documentare un progetto legato al software.
```
Questo è solo un piccolo suggerimento per evitare una ripetizione :)

2024-07-27 21:56 UTC, serenasensini reviewed
Ottimo capitolo, e tra quelli che ritengo fondamentali. Parlando di fornire esempi pratici, mi sarebbe piaciuto leggere qualche esempio di come strutturare dei documenti tra quelli citati (lato sviluppo), anche se a grandi linee. Una delle difficoltà che ho riscontrato nel tempo era trovare dei riferimenti sul punto di inizio con cui scrivere alcuni documenti, e quindi la necessità di dovermi affidare a dei template che ho dovuto poi riadattare. Sapere che per alcuni documenti ci sono delle linee guida di massima sui contenuti potrebbe essere interessante, oltre che utile, IMHO! 

Per il resto, complimenti perché è scorrevolissimo e ben organizzato.

2024-07-27 21:56 UTC, serenasensini commented on docs/it/documentazione.md
> +La documentazione del software è spesso vista come un'attività secondaria, e viene spesso trascurata in favore dello sviluppo del codice. Tuttavia, sottovalutarne l'importanza può avere conseguenze s
```suggestion
La documentazione del software è spesso vista come un'attività secondaria, e viene trascurata in favore dello sviluppo del codice. Tuttavia, sottovalutarne l'importanza può avere conseguenze significative sul ciclo di vita del software e sulla sua gestione dello stesso a lungo termine.
```

2024-07-30 05:36 UTC, BrianAtzori approved these changes

2024-07-30 10:07 UTC, federico-trotta commented
@Cadienvan con gli ultimi commit, penso di aver messo tutto quello di cui avevano discusso ormai secoli fa... XD

Lascerei a te e @elgorditosalsero di rivedere bene le parti di gestione delle specifiche tecniche e di testing perché sicuramente avete più esperienza di me in questo. :)

Per il resto, mancasse qualcosa in generale, resto a disposizione.

2024-07-30 15:28 UTC, elgorditosalsero approved these changes

2024-07-30 15:35 UTC, corradopetrelli approved these changes

2024-07-30 15:50 UTC, merged