Aggiunta capitolo DDD
Il-Libro-Open-Source/book pull request #227
Opened 2024-05-10 14:10 UTC by baldarn

Vedi
https://github.com/Il-Libro-Open-Source/book/issues/226

2024-05-14 09:18 UTC, baldarn commented
@BrianAtzori @Cadienvan wdyt?

2024-05-18 10:07 UTC, BrianAtzori requested changes
Per me il contenuto è buono, c'`e solo qualche errorino da sistemare ma a me fila ed è tutto chiaro! 
Lascio la parola anche ad altri ambassador che hanno una seniority piu' navigata rispetto alla mia per un giudizio sui contenuti, ma per me hai prodotto un bel testo, bravo!

2024-05-18 10:07 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +Forniscono un meccanismo per accedere agli aggregati o entità, astraggendo la logica di accesso ai dati dietro un'interfaccia più orientata al dominio.
```suggestion
Forniscono un meccanismo per accedere agli aggregati o entità, astraendo la logica di accesso ai dati dietro un'interfaccia più orientata al dominio.
```

Verbo tosto da coniugare 😁

2024-05-18 10:07 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +Sono oggetti che non possiedono una identità e sono definiti solo dai loro attributi. Sono immutabili, il che significa che una volta creati, i loro dati non possono essere modificati.
```suggestion
Sono oggetti che non possiedono un'identità e sono definiti solo dai loro attributi. Sono immutabili, il che significa che una volta creati, i loro dati non possono essere modificati.
```

2024-05-18 10:07 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +In questo livello di cooperazione, due o più team lavorano insieme verso obiettivi comuni, coordinando strettiamente le loro attività. Questo richiede una comunicazione frequente e un alto livello di
```suggestion
In questo livello di cooperazione, due o più team lavorano insieme verso obiettivi comuni, coordinando strettamente le loro attività. Questo richiede una comunicazione frequente e un alto livello di collaborazione per assicurarsi che i cambiamenti in un contesto non abbiano impatti negativi sugli altri.
```

2024-05-18 14:56 UTC, Cadienvan commented
Non sono sparito! Ahah sabato prossimo mi sono preso un momento per leggere come si deve il contenuto! Scusatemi ma tra mille impegni e tutti i capitoli in corso devo sdoppiarmi!

2024-05-27 18:33 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +Il termine é stato coniato da Eric Evans nel suo libro `Domain-Driven Design: Tackling Complexity in the Heart of Software` pubblicato nel 2003
```suggestion
Il termine é stato coniato da Eric Evans nel suo libro `Domain-Driven Design: Tackling Complexity in the Heart of Software` pubblicato nel 2003.
```

2024-05-27 18:34 UTC, Cadienvan reviewed
Il contenuto mi torna, farei una introduzione più approfondita del contesto in cui spicca il DDD e il perché dovrei considerare l'adozione di questa metodologia nella mia quotidianità. Considerando il target entry-level del libro, ho paura che si perda il "perché", mentre il "cosa" è piuttosto chiaro e ben definito!

2024-05-29 19:04 UTC, BrianAtzori approved these changes
Mi torna tutto! 
Come sempre passo la palla a qualche ambassador più navigato per un'ulteriore conferma ma secondo me ci siamo, ho visto che hai approvato anche i change che ti ho suggerito quindi top, grande! 🙌🏻

2024-06-25 19:35 UTC, Cadienvan commented
Ciao @baldarn cosa ne pensi del mio suggerimento sull'intro esplicativa?

2024-06-26 07:22 UTC, baldarn commented
@Cadienvan ho scritto una breve intro con pro e contro, se è ok mergiamo, poi arriverà gente che aggiungerà/toglierà cose, io sono solo un dilettante XD

2024-06-26 20:17 UTC, BrianAtzori requested changes

2024-06-26 20:17 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +## Vantaggi del Domain Driven Design
```suggestion
## Vantaggi del Domain-Driven Design
```
Qui scegli tu, ho visto che sotto hai utilizzato il trattino e suggerisco di uniformare, scegli tu se aggiungerlo o toglierlo dove manca/c'e

2024-06-26 20:17 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +- Qualità del codice: Promuovendo pratiche di buon design come l'incapsulamento e la separazione delle preoccupazioni, il DDD conduce a un codice di alta qualità e ben strutturato.
La nostra lingua non si sposa molto con i termini del nostro lavoro 🤣 
Separazione di preoccupazioni è corretto sintatticamente/grammaticalmente ma forse è meglio tradurlo con "compiti" intesto come "che concerne", che ne pensi? :)

2024-06-26 20:17 UTC, BrianAtzori commented on docs/it/domain-driven-design.md
> +- Qualità del codice: Promuovendo pratiche di buon design come l'incapsulamento e la separazione delle preoccupazioni, il DDD conduce a un codice di alta qualità e ben strutturato.
```suggestion
- Qualità del codice: Promuovendo pratiche di buon design come l'incapsulamento e la separazione delle preoccupazioni, sfruttando il DDD è possibile produrre del codice di alta qualità e ben strutturato.
```

2024-06-27 07:19 UTC, baldarn commented on docs/it/domain-driven-design.md
> +- Qualità del codice: Promuovendo pratiche di buon design come l'incapsulamento e la separazione delle preoccupazioni, il DDD conduce a un codice di alta qualità e ben strutturato.
si vede che chatgpt ci ha messo lo sampino? XD

2024-06-27 19:55 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +## Pro / Cons
```suggestion
## Perché?

Come sempre nel mondo dello sviluppo, non esiste una soluzione universale, e il DDD non fa eccezione. Pro e contro di questa metodologia sono stati discussi in lungo e in largo, e la sua applicazione dipende da molti fattori, come la dimensione del progetto, la complessità del dominio, il numero di sviluppatori coinvolti e la loro esperienza.
Di seguito, abbiamo voluto elencare alcuni dei principali vantaggi e svantaggi del Domain-Driven Design.

A prescindere da questi pro e contro, riteniamo utile per chiunque lavori nel campo dello sviluppo software conoscere il DDD e le sue best practices, in modo da poter valutare se e come applicarlo nei propri progetti.
```

@baldarn cosa ne pensi??

2024-06-27 19:55 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +## Perché usare il Domain Driven Design?
```suggestion
### Perché usare il Domain Driven Design?
```

2024-06-27 19:55 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +## Vantaggi del Domain-Driven Design
```suggestion
### Vantaggi del Domain-Driven Design
```

2024-06-27 19:55 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +## Svantaggi del Domain-Driven Design
```suggestion
### Svantaggi del Domain-Driven Design
```

2024-07-09 11:58 UTC, Cadienvan approved these changes

2024-07-09 11:59 UTC, Cadienvan commented
@baldarn ho richiesto la review a un po' di Ambassador, vediamo cosa dicono! ;)

2024-07-13 15:31 UTC, BrianAtzori submitted a review, later dismissed

2024-08-07 13:48 UTC, AngeloAvv requested changes
Ottimo capitolo!

Segnalo giusto due typo (maiuscole/minuscole) e se ti va puoi approfittarne per sostituire i trattini con gli asterischi per sfruttare al meglio markdown

2024-08-07 13:48 UTC, AngeloAvv commented on docs/it/domain-driven-design.md
> +il concetto di Bounded Context è essenziale per gestire la complessità nei grandi sistemi software. Un Bounded Context delimita la pertinenza di un particolare modello di dominio, creando chiari conf
Typo

```suggestion
Il concetto di Bounded Context è essenziale per gestire la complessità nei grandi sistemi software. Un Bounded Context delimita la pertinenza di un particolare modello di dominio, creando chiari confini all'interno dei quali un modello specifico è definito e applicabile. Questo permette di mantenere la coerenza del modello all'interno di quel contesto, pur permettendo l'esistenza di differenti modelli in altri contesti all'interno dello stesso sistema.
```

2024-08-07 13:48 UTC, AngeloAvv commented on docs/it/domain-driven-design.md
> +la cooperazione tra i diversi Bounded Contexts è cruciale per il funzionamento complessivo del sistema. Eric Evans, descrive vari livelli di cooperazione tra i Bounded Contexts per gestire come quest
Typo

```suggestion
La cooperazione tra i diversi Bounded Contexts è cruciale per il funzionamento complessivo del sistema. Eric Evans descrive vari livelli di cooperazione tra i Bounded Contexts per gestire come questi si relazionano e interagiscono. Ecco una panoramica di questi livelli di cooperazione:
```

2024-08-17 13:32 UTC, Cadienvan commented
Mi sembra un ottimo consiglio. @baldarn se sei in ferie scusa il ping, altrimenti attendo che porti dentro i suggerimenti ed eventualmente la modifica e dovremmo esserci!

2024-08-17 19:05 UTC, Cadienvan approved these changes

2024-08-19 14:51 UTC, AngeloAvv submitted a review, later dismissed

2024-08-23 06:58 UTC, guizzo approved these changes
@baldarn A me sembra un buon contenuto 👍 

Ho aggiunto qualche suggestions ma sentiti libero di valutare tu stesso se è il caso o meno di introdurle all'interno del capitolo.

In ogni caso ti approvo la review, ottimo lavoro 💪

2024-08-23 06:58 UTC, guizzo commented on docs/it/domain-driven-design.md
> +La relazione tra modelli in differenti Bounded Contexts può essere mappata attraverso pattern come Shared Kernel, Customer/Supplier, Conformist, o Partnership, facilitando la gestione delle interazio
```suggestion
La relazione tra modelli in differenti Bounded Contexts può essere mappata attraverso pattern come Shared Kernel, Customer/Supplier, Conformist o Partnership, facilitando la gestione delle interazioni tra team diversi che lavorano in contesti distinti.
```

2024-08-23 06:58 UTC, guizzo commented on docs/it/domain-driven-design.md
> +Poiché tutti i cambiamenti sono registrati come eventi, l'event sourcing fornisce automaticamente un tracciato completo e auditable delle modifiche. Questo è particolarmente utile in domini come la f
```suggestion
Poiché tutti i cambiamenti sono registrati come eventi, l'event sourcing fornisce automaticamente un tracciato completo e verificabile delle modifiche. Questo è particolarmente utile in domini come la finanza o la salute, dove la tracciabilità e l'audit sono cruciali.
```

2024-08-23 06:58 UTC, guizzo commented on docs/it/domain-driven-design.md
> +L'immagazzinamento degli eventi piuttosto che degli stati rende più facile recuperare da errori o disastri. Se lo stato corrente viene perso o corrotto, può essere ricostruito riproducendo gli eventi
```suggestion
L'immagazzinamento degli eventi piuttosto che degli stati rende più facile il recupero in caso di errori o disastri. Se lo stato corrente viene perso o corrotto, può essere ricostruito riproducendo gli eventi.
```

2024-09-05 19:19 UTC, Cadienvan approved these changes

2024-09-06 06:57 UTC, guizzo submitted a review, later dismissed

2024-09-15 15:26 UTC, AngeloAvv submitted a review, later dismissed

2024-09-16 19:18 UTC, BrianAtzori submitted a review, later dismissed

2024-10-31 08:11 UTC, Cadienvan commented
Viste le modifiche ai criteri di approval, 3+1 è ora un numero sufficiente per pubblicare il contenuto! Congratulazioni @baldarn per essere diventato ufficialmente parte di questo progetto e grazie infinite per il tuo supporto, tra pochi minuti il capitolo sarà online!

2024-10-31 08:11 UTC, Cadienvan commented on docs/it/domain-driven-design.md
> +nav_order: 12
```suggestion
nav_order: 19
```

2024-10-31 08:13 UTC, merged