Add/refactoring
Il-Libro-Open-Source/book pull request #228
Opened 2024-05-13 10:52 UTC by mrkrash

2024-05-13 10:53 UTC, Cadienvan commented on docs/it/refactoring.md
> +function applyDiscount() {
```suggestion
function getAmountWithAppliedDiscount() {
```

2024-05-13 10:56 UTC, Cadienvan commented on docs/it/refactoring.md
> +Quando ci si trova davanti a del codice che necessita di refactoring a tutti è sorto il dubbio: ma non faccio prima a riscriverlo da capo? Questa domanda ce la poniamo, in genere, perché, basandoci s
```suggestion
Quando ci si trova davanti a del codice che necessita di refactoring a tutti è sorto il dubbio: "ma non faccio prima a riscriverlo da capo?"
Questa domanda ce la poniamo, in genere, perché, basandoci sull'esperienza acquisita, ci convinciamo che saremmo più veloci a riscrivere tutto e otterremmo un risultato decisamente migliore. Ma, forse, non stiamo tenendo conto di due fattori fondamentali:
```

2024-05-13 10:58 UTC, Cadienvan commented on docs/it/refactoring.md
> +* il nuovo codice dovrebbe andare incontro a successive revisioni e riscritture, se non nuovi test.
```suggestion
- L'attività di refactoring non dovrebbe alterare il comportamento attuale, e lo stesso dovrebbe valere per i test.
- Scrivendo nuovo codice, potremmo andare incontro a successive revisioni e riscritture, e avremmo necessità di scrivere nuovi test.
```

2024-05-13 11:01 UTC, Cadienvan commented
@AngeloAvv abbiamo spostato la PR e ripristinato il tuo commento non risolto.
@mrkrash ha rivisto la sezione "Refactoring vs Riscrittura", ora ti torna?

2024-05-13 11:01 UTC, Cadienvan commented on docs/it/refactoring.md
> +Inoltre, nei linguaggi tipizzati, potremmo verificare se c'è la possibilità di rendere detta firma più stringente, ammettendo e/o restituendo tipi meno generici.
Riporto il commento di Angelo:
Qui sottolineerei che è importante farlo solo nelle major updates, e che sarebbe preferibile utilizzare in prima battuta delle keywords o delle annotazioni speciali come @deprecated per comunicare a chi utilizza quei metodi che quei parametri non saranno più utilizzati a posteriori.

2024-05-13 11:04 UTC, Cadienvan commented on docs/it/refactoring.md
> +Inoltre, nei linguaggi tipizzati, potremmo verificare se c'è la possibilità di rendere detta firma più stringente, ammettendo e/o restituendo tipi meno generici.
Mi torna quanto dice Angelo.
Aggiungerei un paragrafo sotto a questi esprimendo che quando si lavora su un prodotto utilizzato da altre persone, specialmente se esterne alla propria azienda o al proprio team, sarebbe meglio adottare un approccio di deprecation nel quale prima si indicano come deprecate le firme dei metodi o parte di esse, e solo ad una data stabilita e comunicata si proceda con la rimozione.

2024-05-18 14:28 UTC, Cadienvan commented on docs/it/refactoring.md
> +Ad esempio potremmo avere un metodo che, nella prima stesura, aveva necessità di numerose informazioni, ma, con successive riscritture, alcune di queste risultaino superflue e non utilizzate.
```suggestion
Ad esempio potremmo avere un metodo che, nella prima stesura, aveva necessità di numerose informazioni, ma, con successive riscritture, alcune di queste risultino superflue e non utilizzate.
```

2024-05-18 14:29 UTC, Cadienvan commented on docs/it/refactoring.md
> +Oppure, un altro esempio potrebbe essere quello in cui gli passiamo numerose informazioni che potrebbero diventare proprietà di uno o più aggregati. Questo è particolarmente vero nei linguaggi tipizz
```suggestion
Un altro caso può essere quello in cui passiamo numerose informazioni che potrebbero diventare proprietà di uno o più aggregati. Questo è particolarmente vero nei linguaggi tipizzati, dove potremmo verificare la possibilità di rendere detta firma più stringente, aggregando e/o restituendo tipi meno generici.
```

2024-05-18 14:37 UTC, Cadienvan commented on docs/it/refactoring.md
> +Questo non significa che non sia possibile farlo ma che bisogna agire con maggiore cautela, adottando un giusto percorso di _deprecation_. Deprecare una firma, o parte di essa, indicando quando quell
```suggestion
Questo non significa che non sia possibile farlo ma che bisogna agire con maggiore cautela, adottando un giusto percorso di _deprecation_. Deprecare una firma, o parte di essa, indicando quando quella firma stessa terminerà di funzionare e quali alternative adottare, dando quindi la possibilità a chi utilizza il nostro software e quel metodo in particolare di adeguarsi, è di sicuro la strada da seguire.
```

2024-05-18 14:38 UTC, Cadienvan reviewed
Proposto solo un suggerimento, semplificando la frase e integrando con un esempio, dimmi se ti piace!

2024-05-27 19:17 UTC, Cadienvan approved these changes

2024-05-27 19:18 UTC, Cadienvan commented
@mrkrash mi sembra un gran bel contenuto! Chiedo review a qualche Ambassador!

2024-05-27 19:27 UTC, akelity reviewed
Super bello,
Forse però all'inizio metterei un paragrafo per approfondire i "motivi" per cui può essere necessario un refactring spiegando che alcune volte potrebbe essere necessario ridurre la leggibilità in favore di altro (ad esempio performance o disaccoppiamento) o viceversa.

2024-05-27 19:31 UTC, Cadienvan commented
Ciao @akelity vedo che finalmente hai messo a posto le notifiche di Github ahahahaah
Potrei essere d'accordo, ma faccio un po' fatica a capire il "come", a tutti gli effetti fino a riga 37 parliamo del "cosa" e del "perché", non saprei suggerire un paragrafo o due in aggiunta.. Hai qualche idea?

2024-05-27 19:35 UTC, akelity commented
@Cadienvan secondo me basta all'inizio un piccolo paragrafo specificando che il motivo del refactring può variare in base al caso e che questi casi possono essere "migliore leggibilità", "migliori performance" etc. Per ognuna spiegherei cosa si intende (una frase) e poi specificherei che l'ottimale è raggiungere tutte ma che non sempre è possibile (per questioni tecniche e di tempo necessario)

2024-05-27 19:37 UTC, akelity commented
Andrebbe bene dentro*benefici* giusto un paio di frasi per spiegare questo concetto.

2024-05-28 20:27 UTC, mrkrash commented on docs/it/refactoring.md
> +`function updateAddress(userId: number, street: string, city: string, zipCode: string, country: string): void {}`
Son d'accordo. Correggo subito.

2024-05-28 21:08 UTC, corradopetrelli requested changes

2024-05-29 06:53 UTC, nicolaerario approved these changes

2024-05-31 09:14 UTC, Cadienvan commented
@mrkrash sono d'accordo sul suggerimento di @akelity , che ne pensi?

2024-05-31 09:23 UTC, mrkrash commented
> @mrkrash sono d'accordo sul suggerimento di @akelity , che ne pensi?

Ho letto i suggerimenti ma, all'atto pratico, significherebbe duplicare concetti piuttosto che riformulare quanto esposto. Sto cercando di capire come poter fare ciò senza appunto duplicarli, cosa che odio profondamente.

2024-06-01 16:32 UTC, Cadienvan commented
@mrkrash in definitiva il capitolo è tuo, di conseguenza se pensi che il contenuto sia già sufficientemente esplicativo possiamo anche procedere. Il punto non è quello di accettare ogni suggerimento ricevuto, quanto di valutarlo!

@akelity sei d'accordo? Come già accennavo, a tutti gli effetti credo che leggere con attenzione il capitolo sia sufficiente a fornire le risposte necessarie, quindi se Mario non dovesse trovare un'alternativa, personalmente approverei comunque il contenuto.

2024-06-01 16:46 UTC, nicolaerario commented
> @mrkrash in definitiva il capitolo è tuo, di conseguenza se pensi che il contenuto sia già sufficientemente esplicativo possiamo anche procedere. Il punto non è quello di accettare ogni suggerimento ricevuto, quanto di valutarlo!
> 
> @akelity sei d'accordo? Come già accennavo, a tutti gli effetti credo che leggere con attenzione il capitolo sia sufficiente a fornire le risposte necessarie, quindi se Mario non dovesse trovare un'alternativa, personalmente approverei comunque il contenuto.

In realtà il capitolo è di tutti. Cosa voglio dire: se oggi il capitolo partorito da @mrkrash è corretto, rispecchia la sua volontà ed è accettato dalle review, può essere tranquillamente mergiato.
Domani io ho delle idee da integrare? Bene, nuova PR e si va. 
E' lo spirito giusto, no?

2024-06-01 16:48 UTC, nicolaerario approved these changes

2024-06-01 17:07 UTC, akelity commented
> @mrkrash in definitiva il capitolo è tuo, di conseguenza se pensi che il contenuto sia già sufficientemente esplicativo possiamo anche procedere. Il punto non è quello di accettare ogni suggerimento ricevuto, quanto di valutarlo!
> 
> @akelity sei d'accordo? Come già accennavo, a tutti gli effetti credo che leggere con attenzione il capitolo sia sufficiente a fornire le risposte necessarie, quindi se Mario non dovesse trovare un'alternativa, personalmente approverei comunque il contenuto.

Ma si assolutamente!
Era sono un feedback il mio! 😉

2024-06-01 17:10 UTC, Cadienvan commented
Sì bravo @nicolaerario intendevo proprio quello 🤣

2024-06-03 07:52 UTC, akelity submitted a review, later dismissed
Come detto, aggiungiamolo se poi ci sono modifiche si vedranno in seguito :)

2024-06-03 18:40 UTC, Cadienvan submitted a review, later dismissed

2024-06-26 07:19 UTC, imD3v submitted a review, later dismissed

2024-06-26 07:24 UTC, corradopetrelli submitted a review, later dismissed
Ottimo!

2024-06-26 15:08 UTC, AngeloAvv approved these changes
LGTM!! :bomb: 

Valutate se è il caso di portar dentro il mio nitpicking :)

2024-06-26 22:20 UTC, mrkrash commented on docs/it/refactoring.md
> +}
Sì, hai ragione. Dato che il libro è in italiano, sarebbe opportuno secondo te utilizzare anche nel codice l'italiano? Sono abituato a utilizzare esclusivamente l'inglese e opterei per quest'ultimo ma, accetto consigli

2024-06-27 06:25 UTC, AngeloAvv commented on docs/it/refactoring.md
> +}
@mrkrash per me è indifferente, il mio appunto riguarda il nome della funzione in Italiano mentre il blocco al suo interno chiama funzioni e usa variabili in Inglese, tutto qui.

Come quick win lato mio puoi semplicemente rinominare la funzione in getNet()

2024-06-27 07:15 UTC, serenasensini reviewed
Ottimo capitolo, chiaro e ben dettagliato!

2024-06-27 07:36 UTC, mrkrash commented on docs/it/refactoring.md
> +}
Si, mi trovi d'accordo. Grazie.

2024-06-27 07:40 UTC, mrkrash commented on docs/it/refactoring.md
> +Un caso semplice, ma spesso presente nel nostro codice, potrebbe essere quello di migliorare le performance rimuovendo le variabili temporanee (il codice che segue è pseudo-codice):
Ok, valuto se riscrivere gli snippet con un linguaggio specifico. Ho optato per del pseudo-codice pensando che un linguaggio specifico potesse essere una barrirera aggiuntiva alla comprensione dello snippet.

2024-06-27 19:37 UTC, Cadienvan commented
Visto che le 6 approval necessarie erano state raggiunte e la revisione grammaticale e di forma di Serena è stata integrata in toto, arriviamo a ben 7 con l'ultima nota pendente riguardante lo pseudo-codice che può benissimo essere accolta in un secondo momento!

Complimenti @mrkrash , tra pochi minuti il tuo capitolo sarà online!

2024-06-27 19:38 UTC, Cadienvan commented on docs/it/refactoring.md
> +# Refactor
```suggestion
---
layout: default
title: Refactor
nav_order: 14
---

<!-- prettier-ignore-start -->
# Refactor
{: .no_toc }

- TOC
{:toc}

<!-- prettier-ignore-end -->
```

2024-06-27 19:39 UTC, merged