docs: implementate le prime versioni di README + AMBASSADORS + CODE_OF_CONDUCT
Il-Libro-Open-Source/book pull request #28
Opened 2023-08-08 14:09 UTC by Cadienvan

Lascio aperta questa PR per qualche giorno per raccogliere le vostre idee e feedback per questa prima versione di README e pagine associate!

2023-08-08 18:16 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +nostracomunità un'esperienza libera da molestie per tutti, indipendentemente
nostra comunità

2023-08-08 18:17 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +dall'età,corporatura, disabilità visibile o meno, etnia,caratteristiche
dall'età,corporatura -> spazio dopo la virgola

2023-08-08 18:17 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +sessuali, identità ed espressione di genere, livello diesperienza, istruzione,
di esperienza

2023-08-08 18:19 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +pellereligione o identità e orientamento sessuale.
pelle, religione

2023-08-08 18:20 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +ambientepositivo per la nostra comunità:
ambiente positivo

2023-08-08 18:22 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +* Dimostrare empatia e gentilezza verso le altre persone* Rispettare le
credo debba essere:
- Dimostrare empatia e gentilezza verso le altre persone
- Rispettare le opinioni...
ecc

2023-08-08 18:22 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +scusarsi verso le persone  colpite dai nostri sbagli, imparando da queste
persone  colpite -> ci sono 2 spazi

2023-08-08 18:23 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +* L'uso di linguaggio o immagini sessualizzate e l'attenzione sessuale o
Stesso discorso dell' elenco puntato sopra

2023-08-08 18:24 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +informazioni private altrui, ad esempio un indirizzo postale o  elettronico,
o  elettronico -> 2 spazi

2023-08-08 18:24 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +ragionevolmente essere considerati  inappropriati in un contesto professionale
considerati  inappropriati -> 2 spazi

2023-08-08 18:25 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +edell'applicazione degli standard di comportamento accettabili e sono tenuti
e dell'

2023-08-08 18:25 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +aintraprendere azioni correttive appropriate ed eque in risposta a qualsiasi
ad intraprendere

2023-08-08 18:25 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +dirimuovere, modificare o rifiutare commenti, commit, codice, modifiche dei
di rimuovere

2023-08-08 18:25 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +wiki,issue e altri contributi non allineati a questo Codice di Comportamento,
wiki, issue

2023-08-08 18:26 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +comunitàche negli spazi pubblici quando un individuo rappresenta la sua
comunita che

2023-08-08 18:26 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +comunità.Esempi di rappresentanza della nostra comunità includono l'uso di un
. Esempi

2023-08-08 18:27 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +indirizzo e-mailufficiale del progetto, la pubblicazione tramite un account
e-mail ufficiale

2023-08-08 18:27 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +ufficiale attraversosocial media o la funzione di rappresentante designato ad
attraverso social

2023-08-08 18:27 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +possonoessere presentate contattando i responsabili dell'applicazione di questo
possono essere

2023-08-08 18:28 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +azionicorrettive contro azioni che ritengono violare questo Codice di Condotta:
azioni correttive

2023-08-08 18:28 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +comportamentigiudicati non professionali o ostili nella community.
od ostili

2023-08-08 18:29 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +inappopriato.Pubbliche scuse potrebbero essere richieste.
. Pubbliche

2023-08-08 18:29 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +comunicazione perun periodo di tempo specificato con le persone coinvolte,
per un

2023-08-08 18:30 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +incluse quelle cheapplicano il Codice di Condotta. Questo comprende
che applicano

2023-08-08 18:30 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +l'inibizione alla partecipazionenegli spazi della comunità come canali esterni
partecipazione negli

2023-08-08 18:31 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +aqualsiasi sorta di interazione o comunicazione con la comunità. Durante
a qualsiasi

2023-08-08 18:31 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +coinvolte,comprese coloro che applicano il Codice di Condotta.Violare questi
. Violare

2023-08-08 18:31 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +standarddella comunità, inclusa la ripetezione di comportamenti inappropriati,
standard della

2023-08-08 18:32 UTC, nicolaerario commented on CODE_OF_CONDUCT.md
> +molestieo aggressioni individuali o denigrazione di gruppi di individui.
molestie o

2023-08-08 18:36 UTC, nicolaerario requested changes
Ho lasciato vari commenti soprattutto riguardo la formattazione del testo;
Per quanto riguarda gli elenchi puntati consiglio `- ` : dando shift+invio ti crea in automagico quello sotto.

Consiglio `Prettier` anche per gli MD

2023-08-08 19:11 UTC, gallottino commented on CODE_OF_CONDUCT.md
> +Nell'interesse della promozione di un ambiente aperto e accogliente,
In realtà _"e accongliente"_ è corretto: [utilizzo della 'd' eufonica](https://www.treccani.it/enciclopedia/d-eufonica_(La-grammatica-italiana))

2023-08-09 07:06 UTC, Cadienvan commented on CODE_OF_CONDUCT.md
> +noicontributori e manutentori ci impegnamo a rendere la partecipazione alla
![image](https://github.com/Il-Libro-Open-Source/book/assets/5492927/5e46626b-0a06-409c-8ecc-a9f02df3eca0)

2023-08-09 07:15 UTC, Cadienvan commented
Ciao @nicolaerario , grazie mille ho corretto il correggibile ahahahah

2023-08-09 07:26 UTC, nicolaerario commented
Great @Cadienvan

2023-08-09 07:28 UTC, guizzo approved these changes
A me sembra tutto ok 👍

2023-08-10 10:09 UTC, elgorditosalsero approved these changes

2023-08-11 07:03 UTC, merged