Fixa errore nel README.md
Il-Libro-Open-Source/book pull request #61
Opened 2023-09-15 07:28 UTC by garak

Fix #44

2023-09-15 07:31 UTC, Cadienvan requested changes
Rimuoverei anche il "che" come avevi giustamente suggerito :)

2023-09-15 07:33 UTC, garak commented on README.md
> +Sono coloro che hanno deciso di contribuire al progetto in maniera diretta, prendendosi la responsabilità di uno o più capitoli, oppure che di altre aree come la grafica, la traduzione, la revisione,
Fatto. Fatemi sapere se avete bisogno di uno squash o se preferite farlo durante il merge

2023-09-15 08:20 UTC, guizzo commented on README.md
> +Sono coloro che hanno deciso di contribuire al progetto in maniera diretta, prendendosi la responsabilità di uno o più capitoli, oppure che di altre aree come la grafica, la traduzione, la revisione,
@garak Se riesci a fare lo squash sarebbe fantastico 😃

2023-09-15 08:44 UTC, Cadienvan approved these changes

2023-09-15 08:58 UTC, guizzo approved these changes
LGTM

2023-09-16 06:10 UTC, eppak commented on README.md
> +Sono coloro che hanno deciso di contribuire al progetto in maniera diretta, prendendosi la responsabilità di uno o più capitoli, oppure che di altre aree come la grafica, la traduzione, la revisione,
Si potrebbe togliere "oppure che" (virgola compresa) e usare la congiunzione "e"

2023-09-16 12:44 UTC, merged